namespace Terrasoft.Configuration
{
	using System;

	#region Class: BaseStorableEntity

	/// <summary>
	/// Base storable entity with autogenerated id.
	/// </summary>
	[Serializable]
	public class BaseStorableEntity
	{
		
		#region Properties: Public
		
		/// <summary>
		/// Entity id.
		/// </summary>
		private Guid _id;
		public Guid Id {
			get => _id == Guid.Empty ? (_id = Guid.NewGuid()) : _id;
			set => _id = value;
		}

		#endregion

	}

	#endregion
} 




