namespace Terrasoft.Configuration.Translation
{
	using System;
	using Terrasoft.Core.Translation;

	#region Class: LocalizableItem

	public class LocalizableItem : ILocalizableItem
	{

		#region Constructors: Public

		public LocalizableItem(string key, string value, Guid cultureId, DateTime modifiedOn, bool isAutogenerated) {
			Key = key;
			Value = value;
			CultureId = cultureId;
			ModifiedOn = modifiedOn;
			IsAutogenerated = isAutogenerated;
		}

		#endregion

		#region Properties: Public

		/// <summary>
		/// Key.
		/// </summary>
		public string Key {
			get;
			private set;
		}

		/// <summary>
		/// Value.
		/// </summary>
		public string Value {
			get;
			private set;
		}

		/// <summary>
		/// Culture identifier.
		/// </summary>
		public Guid CultureId {
			get;
			private set;
		}

		/// <summary>
		/// Modification date.
		/// </summary>
		public DateTime ModifiedOn {
			get;
			private set;
		}

		/// <summary>
		/// Determines if value is autogenerated.
		/// </summary>
		public bool IsAutogenerated {
			get;
			private set;
		}

		#endregion

	}

	#endregion

}













