define('ProcessProgressSpinnerImage', ['ext-base', 'terrasoft'],
		function(Ext, Terrasoft) {

			var image = "background-image: url('data:image/gif;base64, R0lGODlhHgAeAOZcAP39/f7+/urq6tzc3NXV1c7OzuPj4" +
					"7i4uMbGxrGxsfv7+7+/v6mpqaKiovn5+fz8/Pf39/T09Pr6+u7u7vPz8+zs7PX19fb29vj4+NfX1+jo6Ovr6+bm5uTk5O3t" +
					"7fDw8O/v7/Hx8eLi4tPT0+Hh4d3d3cDAwOfn597e3tnZ2enp6eXl5dHR0d/f39ra2tvb28fHx8rKyuDg4Lq6urW1tcjIyMT" +
					"ExM/Pz8LCwrOzs9LS0ry8vMzMzM3Nzb6+vtjY2NTU1K+vr7KystDQ0MvLy8XFxdbW1snJycHBwa2traurq7m5ube3t7u7u7" +
					"29vaqqqsPDw7CwsLa2tqysrK6urqioqLS0tKOjo6enp6SkpKWlpfLy8v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
					"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
					"AAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh/wtYTVAgRGF0YVhNUDw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1" +
					"wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2" +
					"JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYge" +
					"G1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlv" +
					"biByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmV" +
					"mPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy" +
					"5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDo0QTFCNEMzNDM3M0RFMjExO" +
					"DA2N0I4OTI1MTJENDA2QSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDo2MDFCMzM1NEYwNzgxMUUyQTY0MUE2QTU1NjEw" +
					"M0NENSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDo2MDFCMzM1M0YwNzgxMUUyQTY0MUE2QTU1NjEwM0NENSIgeG1wOkN" +
					"yZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1LjEgV2luZG93cyI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbn" +
					"N0YW5jZUlEPSJ4bXAuaWlkOjBFNjIzMDc4NDg0NEUyMTE4MDY3Qjg5MjUxMkQ0MDZBIiBzdFJlZjpkb2N1bWVudElEPSJ4b" +
					"XAuZGlkOjRBMUI0QzM0MzczREUyMTE4MDY3Qjg5MjUxMkQ0MDZBIi8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+" +
					"IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+Af/+/fz7+vn49/b19PPy8fDv7u3s6+rp6Ofm5eTj4uHg397d3Nv" +
					"a2djX1tXU09LR0M/OzczLysnIx8bFxMPCwcC/vr28u7q5uLe2tbSzsrGwr66trKuqqainpqWko6KhoJ+enZybmpmYl5aVlJ" +
					"OSkZCPjo2Mi4qJiIeGhYSDgoGAf359fHt6eXh3dnV0c3JxcG9ubWxramloZ2ZlZGNiYWBfXl1cW1pZWFdWVVRTUlFQT05NT" +
					"EtKSUhHRkVEQ0JBQD8+PTw7Ojk4NzY1NDMyMTAvLi0sKyopKCcmJSQjIiEgHx4dHBsaGRgXFhUUExIREA8ODQwLCgkIBwYF" +
					"BAMCAQAAIfkEBQoAXAAsAAAAAB4AHgAAB/+AXIKDhIMHVVUWhYuMgg8bhDkNDRGDChgBjYUiOVQQg5KUgxFbFA+ag04MDEe" +
					"gk5VcDluzmahcE08MTxOCoZUBs1sOtoMxqzu9r1wQs7CNFACDEFSrJFy+AMEKgw8fn4IAMzsngxmrQg8vQEASzFsXggEUGw" +
					"IVtSkJ+TBbXABSNB0WOYC2rIKAgxuGcVlxIF8CITokbInW6MGEgwc/nLKUIYdDHLYCGBTgQeGiCzHykbMFoQI8WxtGEAPHS" +
					"IGEmzgpEougoqdPFTsOCB1aYiaXLQaSKjUQdKjQojORLk1aBInVqyKMAnDAtatJQrWIbfiGqkINXrYoDBigYhujCCymFiyI" +
					"EbYRibUDSkyoq+CFCbkLijhbBACDAg14B5CAFcIGYBwoHjzIEGLRhxQuMl0wgFeAIwRyR3wjgQABiQcaNGwA8IMAAUiCtrR" +
					"AoVMDERDSapQG4aBAAZkTXGdw249sPEI/SmeI5VsmlxKuA878ULrGp96/BUVwTeAlqgBDSssQhN05FwOuURC7QAQBkY3lB0" +
					"kwksHDTAUyPJNvTmjLRqOExEdMIAAh+QQFCgBcACwAAAAAHgAeAAAH/4BcgoOEg05BQReFi4yDHoQHDAwWgys3Co2FKzM0G" +
					"IORk4IACQ1KApmDOAkJBZ+SlFwEDQ0MnqhcIKsJIIKglBBVsxm3gzerOL2vXDCzCQCZEYQYNKsdXL4TV7McgwAWEoRIOKeC" +
					"LqtLXCgZw8wNPoMQW1sUgwMH9zz0XDs73IQAP6Zs4eKAgjx5mLicWHDvwBIjCvQxAgAgwsEtFp4NeuBiRsMaxAxuiZBwEYQ" +
					"b91QQk7DFATEPw4hxCdBIgc2bMgVBmMCz5wQoC4IKJZHTgoCjSAUAFRqUqEyjSY8SqUG16oqcXG5qxcoIhMtbE258IGbBgI" +
					"EJDxpdyIAAwRBiGpzMGugwsFALGG0R8FDUKICDBx7kGjgBQdAWInlriBD0oi4hCjJkCMIQ1ywvQT3a/rC1okCBDgA2bJjAp" +
					"cWAAaQFRVhxdZAAFiEGYbjhOYQEAgRScAlxukQhW41KeB7A5XZuQSJOq5S5xfMNT8Z1c4FwegBwVEY8WyuOWzoXDae3o4Kg" +
					"o4COQdEHKSiBYiyxBx0qoO9OKBpXQumJBQIAIfkECQoAXAAsAAAAAB4AHgAAB/+AXIKDhINQUlIQhYuMggAThD4JCReDJyO" +
					"NiycmO5GTlYJMDEIVmYM1BweYgpKUgikMDEEOpoIfqQcfrJ9cGEGxLrWDI6k1u648sQcBmRaFO6kcXK0XIE+xGoMfOy+EMD" +
					"WlgiipJgAkLi4KRLE2gg4xWQ1KEoIyC/csEYI4ONmEAS+EcAHwg0GDg1lECBJQ5N4CE930ZQoh5ODBHboIocDhsEctCUoOB" +
					"lHYaMS9DcJeYCEAoBaIbsICKBJGc5CECDhzRoiBoKfPDjUdbBlKdAtPnz2B0hRadCiLAlCj+ov5oKrVBzUbUVAgLASBLcIw" +
					"CBCwpSUjCC+gGhE2YayADc6SCD3ocCPqiJmNFAAI4VaAB1pcIuiIeoMDAHMSCVngcEKQhLZjKTgaAbUEYA0ECGSbMEEXBwM" +
					"GwAqCUCGcIA8ZRHNxYCTz1gEDZAQG3QGroAD0MonITIKLAtiyuWgADYkmhcwEaP2OLQgDaAOAaw3I7G95cC4VQKsI+4PAD7" +
					"PWB81dIZmmBhCDwg+CYDZreuA0AwEAIfkECQoAXAAsAAAAAB4AHgAAB/+AXIKDhIM1Tk4QhYuMggAfhDYHB4qCKhkKjYUCM" +
					"DgOg5KUjk4JBx6agwULCxmgk5UDCQlSn6hcWyYLJluCoYoONLIltoMZqz29r1xDsj4BmhfPgg5Qqxpcvh+yCQKDITjDjgU3" +
					"E4MkqwgAHSgoCswJNYISBUoMCRKCBgj7GRdcADVqbCgUAMWSCAFeRGHAUEkHQRV47EMAo4UCCwAaAdhygCFDHCEIPRBRY+I" +
					"IWxISMKTxkJGDH/vK2UJB5UdGVCFaEOMSoFKhB0CDPrhJbACNo0hpsCjAtOm1nSMaSJ3aYGlTpk+JRaUqNQOQr2AH7rxQoa" +
					"zZCoykEYPwgBiFFxSliEnYsgWC2kIYSBAgMOAuowh06dYa9ODE3r0pMGgKMPRC4C0RMnG58OOwERUAAHDwh9eDh2cPANOtB" +
					"CDFXhG1KgwYUGEj5AAVBAiwMEgChS1qQZSIULvEagsPDBjgwAWC7A1EGRMkdGI18eDDBU2QzWunhdUl8EEnzkWCbAGSbYlY" +
					"jZbLdm+yQRBz0GJAi5vnHW2o4BMVgArVzQvnPo3oTpH77RQIACH5BAkKAFwALAAAAAAeAB4AAAf/gFyCg4SDBTY2GIWLjII" +
					"AW4QxCwsQgxsuD42FFT1HEoOSlIIBUAcLIJqDIwgIL6CTlVwtBwdOn6lcFDAIMBSCoZUOO7QyuIMDrCO/sFxAtDYBmhDRgh" +
					"IxrBtcwFtLtBWDWzDFjkAEH4MrrD0AHCQkCs4HBdU6QgkHCoInBfwvlQA3bngoFECEiQgBUDBJwFAIB0ETRvArcMPAg2mNA" +
					"lDwwZAhDEiD2N2YmAKXggMMdzxk5KAEv3O4SNAYAADXFgPGuARQtOiBz58PqBlrMaOo0RkZCChdmi1nBgZQozJIulRpU2NP" +
					"pUId4KKr1wk5uUCYQLYs2LCMjggwZoGEhaENoa4UudDIAYcBA0TgChClgV8sOjKF3IAXbwsHqQBEwOHXbxC9YlsULuEBAIA" +
					"NPAlJoOCLiwYrjY84kjzgRD4uHwwY+BDAgoVpFLZsQazzBdTMN+kKUtBBNQQAAgQMlCB7i1AHKlJVUJ0NuHBBEWTHMgZBdY" +
					"d8zgdyeVBcMC4NqmFmH3RBdgRjCjgY4FCTy3hHsmnjAvDhvKPg2ncLRXv/ubFAACH5BAUKAFwALAAAAAAeAB4AAAf/gFyCg" +
					"4SDIzExDoWLjIIAEYQsCAiKgh4oD42FEyNDCoOSlIIBRwtFH5qDKQUFMqCTlSILCzYSqYIWrAUWgqGKElCzHbeDMqwpvbBc" +
					"KbMxAZoOz4IKLKwTXL4UJrPXghQ8BoMBLi9bgxqsIwAqKysPzAsj00ZLBz6fXAIE+yQYXAH7QBQK0AHBhQAifBxYuESDoBA" +
					"p9u078QCDtEUBIthYuJAHBULrjEhEcUvBgoU4HDKSIGKfuVsddrQAcCvCCWKCKhUCwLMngIu3RJgYStQEigFIk3Yj5iKB06" +
					"cJjiZFuvRWU6hORZDYyjUETi4YQIgdK/ArowIViEE4AYEYCQZPrY60ZaRggwEDKjUFkMKgbxIjmQYBANHhrgEO+Bg9+GABQ" +
					"d++NIZxcbDCcIcPAQJ8sFWoRRIqmQTMeNxjFIe7FfBFECAgQgAHsB08adBA3j8UUaLotKDBn6AHG1g7ALBly0cXtLFcGCRB" +
					"QKoQrFERN/4vB+0iXx2w3pBp+kcuGmhf2YBzAmtIXLwPQkKbCbEHFQRUkKZeUAQtVX4AbZRxbvri3wligG9mCQYgToEAACH" +
					"5BAkKAFwALAAAAAAeAB4AAAf/gFyCg4SDKSwsEoWLjIMWhBkFBYQgIo2LISkZkJKENwg8W5eDKAQEHYORk4IcCAgxCqOCEK" +
					"YEEIKqgzGuJ7KDK6YouJ1cJa5DvpCmH1y5ETCuzIIRLByEMiQRgxumKVwVGhrFrj+DLyYLRYMTA+0cDoIvL6KFGj23HTYL+" +
					"yYbghQt2rXbAADeJQsx9u1joY2QhxICUckqsq+GP0YKTrRrOIoDDkuyLlxMRrJkB1coXa0wwLIlPV8lDsiceWBlS5YvZcWk" +
					"KVPDiZ9AOfoKQbRoiJKMdEzw5cCDwVEdEiRYxejBBwEClspyIjWBFW+EAlDYgFVAhQejQlwg0jXBjl5cfxRUKLuhoQW0hUj" +
					"ksCJog4muLAbNFRACL4YtWzBIAAIkhYQoDBhsEkSCiRRCECYoEgQA8RYFERo0SFIsMmlCFUZdQHyBS+jRgmZEPkJSgWcArk" +
					"WfFhD5iYdkERBjmKZ7EILIO3wBoLCFwqDXp7lYmBLkBUnFz4sPsoaUEPRkgQAAIfkECQoAXAAsAAAAAB4AHgAAB/+AXIKDh" +
					"IMoGRkShYuMggEQhAMEBIqCIRwAjYUUMiUPg5KUjgQFIxGagx0DAyqgk5UqBQUsCqiCGKsDGIKhigossgK2gyqrHbyvXCKy" +
					"RgGaCs6CDyirW1y9F7IF1oIXGa2OJyeQghOrLQEgGxsAJLIlggotMAg8n1whBvobtQEkJKcIBRAwAkMADUQQKIThoRsHfQY" +
					"6gAAgIdqiR0MUKsxwQeCHDhDBaXrAQ+GNhoweVNBHDpWKIxwsNsIAYpigSoUC6Nyp0yaXEzyCCuVRQYDRoxZ8kljAtOmCok" +
					"eNJrW51CnTCR6yam1py8GWr2C5+VxkpKYtBRFq2eJw4EDBRgCjLHwNiApK2wNNSmQa9Cgshb0pt0AYcvcADnAPKIQ1KGGHh" +
					"kUdZjTJ5AHBXQKOFG+5sLdHgwY9JCAaoIBJggQuUvlwglNChHtctmj5vMICAwY5uMg4baWlggmoFnz2wcU2bi4BTJwu4JPD" +
					"5ywhit/OzaXC6QTAbQEQ8pmHIOPUuRA5jWPYhycNnjj4Pn3QhRxSUMhs5IDHgEHgCWlYP5ZQ/mGBAAAh+QQJCgBcACwAAAA" +
					"AHgAeAAAH/4BcgoOEgx0oKAqFi4yCAQ6EIgMDioIUKgCNhRccK5mCkpSOLwQpFpqDAgYGE4OhlRUEBBkPqIIOHQYdkFyvXA" +
					"oZsh62gxOrKqCTihyyLwGatYMAK6unrxCyBBSDEC8VgwEeHrxcW6scAVsTEwDMBCKCDwY3BTrRFgL5H7UBJycXhcKlcBBAg" +
					"I4CCG+AEIShQj4BGygEUPCMUQAIRhAifAGBUIAIGx4uRPXgYAECIxcBCJGPnKYKQ1RU1CRhG7FfFgPo3HlTkEEdQINuGUp0" +
					"i0tUHRAoXYqgKNGjmpIyVRqBgtWrEnpKiMC1awRGn4i5CEGsQxAOxFQsMJEBqqAPO6saNBASttGRBXhxyKjrgEgWuQ2UfNA" +
					"EIAI2vHhrbPDJALCWGwok4BCwiIMJJJlAEEHsQpCCKXJN2GTBgAELBS5ctFDg48CBEoM42LCRVVAJKxoGbZlS+l+CBDO4GH" +
					"DdBMMgBYMJ1bVRGgeXC7+DByjiekRPDaWVbHkeXdAE1weSowpwoPQQQdCBDxriugaxEAkYRKmdPrggCDOciJhJc0iLQfURI" +
					"oBbNwVITCAAIfkECQoAXAAsAAAAAB4AHgAAB/+AXIKDhIMCKysPhYuMggEShBoGBoqCFh4AjYUYHhWZgpKUjiIDLRCagyAC" +
					"AluDoZUgAwMon6gKqwIKoJOKDyiyH6iEW6sgu6ICsiKotVwAFasYXK8OsgMWgxgkE4QUEbqWqxUBEVtbAMkDJ4IPJwQEP58" +
					"O5lsWnx4eDosfLRIBHj/evWvFRQEFelsgBKjEKEA1gQRISBsUAAPCCMIApHj3guAiABfMgUMFIsM4YQ9OCRM0kpCDlzAdMB" +
					"RWIYPNmxmqNNjJc8RKUAWCCi2gk+dOnz81DBWaI4jTpyl+FrRAtSq2RQGkovCoiQMNDSs3IIDxQh+jEDgYMDiQFdUNBHCjj" +
					"3RoJuGGErUMhITQBMCCAxdw4RbgxqVCFLxTRihQAGPDIhUwYGQKwSIwCpZC1NrAyIVAggQEFKBAIUKBjQULSAxSQSTGyBYz" +
					"BAyKkOOzCggHDpjgwgE1DrMFuXJpK+jI5xpccOseTgR1BqkCPguhkDz3bi4fUJsQ3tDHZyCClF/vjLrHyi0HEjABJ34QBCQ" +
					"2OhDXJAHIsvDWCVWAJLVQ+5WBAAAh+QQJCgBcACwAAAAAHgAeAAAH/4BcgoOEgyAVFQCFi4yDD4QTAgKKghAfAY2FChRbmI" +
					"KRk4MaBhwOmYMWW1sQg6CUWwYGK5SnD6pbj1yuXAArsRSnhBCqEZ+SihOxGqcftAG3ErrHEh2xrIIOHCGOVEEGgw6qwBAWF" +
					"gHJBhWCABsDAy2ULA3zOx+CEREKixQc+h8t7twV4yJDybwGWWI4oMVIgoiAA0oRUnBDy0EmwQAAHEBi4KIIJuaJCMZlSwkQ" +
					"njJpiEFSUK5CEhzInPkyGIgSOHOWoMKgp88MLblsIEC0KAGePnsCbTnUKNElNKJKHRBUAYSrWK8VShnMgEeVOwSQnFCggIx" +
					"ojLbASJDAB1dGBKXKFhhygqGEEULYJjiwJROACw5ayC1AwJ4uJnpzZFCggIeHRRt6FFC0JYPckVwULGEbw4KgFAcOpFBAgs" +
					"SKB0QQIOgwqIIOFvoEiTCxYVCEGaE3QFiwAAYXFaqPmHIJjBDXAqF7cNndm0sAFqpfBK0Qekkx5r65hFANo/ipADZC/6jEO" +
					"zuXFKpHkKTg44CP2NjB1Yih4S0jBT9Yk2/eKnZQYeW1FAgAIfkEBQoAXAAsAAAAAB4AHgAAB/+AXIKDhIMWW1sAhYuMgg8C" +
					"hBGIioIOEQGNhTJJWBeDkomDEwIVEpmDTA0NRZ+TghcCpJSnFVcNVxWCoIoAFbGep4NFqky6rluxE6ehr1iqKFy7ChuxDoP" +
					"TEYMPVjQrg0CqUw8SDg4ByAIhggAgHQYclAQM8zjqAEFBIosQFQ9cFCsMCOwATISQeQyUFJAQYtYiBRoECtyggJCCEVMQ7g" +
					"gGgIPAE8AWWbAxr0OwaCu2YDol4MbJdYwkyJwpweEyiThpJNjJ08VLLhMGCB06QCfPnT5fBiUqdEGTp1Bb/HyAoapVDIxWn" +
					"uQQMpMAHLmCfSBAoENFRhR4HDhgQ2ujF2ShCWQQ4FBBhiVrDyygkAkABAkG4hJwsUUQCB95Z7h4oIAFiEUTRgBRFKFEXA6O" +
					"TKy9AazEggUlHqxYoeGBjgIFNAwC8eOHP0ErEHgYdAHJZw8OECDowaUC6iGmHFko5HbEZx1ccu8WlAG1jJ8TPpsYrpz3P9Q" +
					"FsgULEOPzgEq6rXNBgTrFyQhFFtg4W32QgxssIJ1UMOCE+/CEPpz9Saj9yUAAOw==')"

			return {
				image:image
			};

		});
