define("AccountResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		AccountCaption: "Account",
		IdCaption: "Id",
		NameCaption: "Name",
		OwnerCaption: "Owner",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		ProcessListenersCaption: "Active processes",
		OwnershipCaption: "Business entity",
		PrimaryContactCaption: "Primary contact",
		ParentCaption: "Parent account",
		IndustryCaption: "Industry",
		CodeCaption: "Code",
		TypeCaption: "Type",
		PhoneCaption: "Primary phone",
		AdditionalPhoneCaption: "Alternate phone",
		FaxCaption: "Fax",
		WebCaption: "Web",
		AddressTypeCaption: "Address type",
		AddressCaption: "Address",
		CityCaption: "City",
		RegionCaption: "State/province",
		ZipCaption: "ZIP/postal code",
		CountryCaption: "Country",
		AccountCategoryCaption: "Category",
		EmployeesNumberCaption: "No. of employees",
		AnnualRevenueCaption: "Annual revenue",
		NotesCaption: "Notes",
		LogoCaption: "Logo",
		AlternativeNameCaption: "Also known as",
		GPSNCaption: "GPS N",
		GPSECaption: "GPS E",
		CompletenessCaption: "Data entry compliance",
		AccountLogoCaption: "Account logo",
		AUMCaption: "AUM",
		LeadConversionScoreCaption: "Lead conversion score",
		PriceListCaption: "Price list"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});