define("ActivityResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		ActivityCaption: "Activity",
		IdCaption: "Id",
		TitleCaption: "Subject",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		StartDateCaption: "Start",
		DueDateCaption: "Due",
		PriorityCaption: "Priority",
		AuthorCaption: "Reporter",
		RemindToAuthorCaption: "Remind reporter",
		RemindToAuthorDateCaption: "Remind author on",
		OwnerCaption: "Owner",
		RemindToOwnerCaption: "Remind owner",
		RemindToOwnerDateCaption: "Remind owner on",
		TypeCaption: "Type",
		ActivityCategoryCaption: "Category",
		ShowInSchedulerCaption: "Show in calendar",
		StatusCaption: "Status",
		ResultCaption: "Result",
		DetailedResultCaption: "Result details",
		TimeZoneCaption: "Time zone",
		AccountCaption: "Account",
		ContactCaption: "Contact",
		SenderCaption: "From",
		RecepientCaption: "To",
		InvoiceCaption: "Invoice",
		CopyRecepientCaption: "Cc",
		BlindCopyRecepientCaption: "Bcc",
		BodyCaption: "Body",
		NotesCaption: "Notes",
		ColorCaption: "Color",
		SendDateCaption: "Sent on",
		EmailSendStatusCaption: "Email status",
		DurationInMinutesCaption: "Duration (minutes)",
		ErrorOnSendCaption: "Email status details",
		DurationInMnutesAndHoursCaption: "Duration (hours, minutes)",
		AllowedResultCaption: "Possible results",
		CreatedByInvCRMCaption: "Created in InvisibleCRM",
		LeadCaption: "Lead",
		MessageTypeCaption: "Message type",
		ProcessListenersCaption: "Active processes",
		IsHtmlBodyCaption: "IsHtmlBody",
		MailHashCaption: "Hash code",
		ProcessElementIdCaption: "Process item",
		GlobalActivityIDCaption: "Outlook activity global identifier",
		UserEmailAddressCaption: "User email",
		EventCaption: "Event",
		OrderCaption: "Order",
		CaseCaption: "Case",
		IsNeedProcessCaption: "Needs processing",
		ActivityConnectionCaption: "Activity",
		ChangeCaption: "Change",
		ReleaseCaption: "Release",
		ProblemCaption: "Problem",
		OrganizerCaption: "Organizer",
		LocationCaption: "Location",
		ConfItemCaption: "Configuration item",
		IsNotPublishedCaption: "Is not published",
		CallDirectionCaption: "Call direction",
		HeaderPropertiesCaption: "Header Properties",
		EnrchEmailDataCaption: "Parsed e-mail",
		EnrichStatusCaption: "Enrichment status",
		ServiceProcessedCaption: "Service processed",
		IsAutoSubmittedCaption: "Is auto submitted",
		SenderContactCaption: "Sender contact",
		OpportunityCaption: "Opportunity",
		ContractCaption: "Contract",
		ProjectCaption: "Project",
		FullProjectNameCaption: "Project",
		PreviewCaption: "Preview",
		OmniChatCaption: "Chat",
		OwnerRoleCaption: "Role",
		RemoteCreatedOnCaption: "Remote calendar created on",
		DocumentCaption: "Document",
		QueueItemCaption: "Queue item"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});