define("AdCampaign_ListPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		ClicksChartWidget_series_0: "Clicks",
		ClicksChartWidget_series_2: "Contacts",
		AmountSpentChartWidget_series_2: "Contacts",
		AmountSpentChartWidget_series_0: "Amount spent, $",
		ContactsIndicatorWidget_title: "Contacts",
		ContactsIndicatorWidget_template: "{0}",
		PDS_CostPerContact: "Cost per Contact",
		PDS_Contacts: "Contacts",
		PDS_CostPerSubmission: "Cost per Submission",
		PDS_Submissions: "Submissions",
		ActionButton_caption: "Actions",
		AdAccountsFacebookContainerAddButton_caption: "Connect account",
		AdAccountsGoogleContainerAddButton_caption: "Connect account",
		AdAccountsQuickFilter_config_caption: "Ad accounts",
		AdAccountsTabContainer_caption: "Ad accounts",
		AdAccountsTabContainerFacebookContainerDescriptionLabel_caption: "Includes ads placement on Facebook, Instagram, Messenger and Audience Network",
		AdAccountsTabContainerFacebookContainerMainLabel_caption: "Facebook",
		AdAccountsTabContainerGoogleContainerDescriptionLabel_caption: "Includes ads placement on Google Search, Display, YouTube and Google Shopping",
		AdAccountsTabContainerGoogleContainerMainLabel_caption: "Google",
		AdAccountsTabContainerHeaderLabel_caption: "Ad accounts",
		AdCampaignListLabel_caption: "Overall performance data",
		AdCampaignStartSyncButton_caption: "Start sync",
		AmountSpentChartWidget_series_1: "Submissions",
		AmountSpentChartWidget_title: "Amount spent dynamics, $",
		AmountSpentIndicatorWidget_template: "{0}",
		AmountSpentIndicatorWidget_title: "Amount spent, $",
		AmountSpentTabConteiner_caption: "Amount spent",
		Button_Data_Import: "Import",
		ClicksChartWidget_series_1: "Submissions",
		ClicksChartWidget_title: "Click dynamics",
		ClicksIndicatorWidget_template: "{0}",
		ClicksIndicatorWidget_title: "Clicks",
		DataGrid_AdAccountsTabContainerFacebookGridDS_ConnectionStatus: "Connection status",
		DataGrid_AdAccountsTabContainerFacebookGridDS_ConnectionStatusDS_Name: "Name",
		DateRangeQuickFilter_config_caption: "Data range",
		DefaultHeaderCaption: "Page title",
		EmptyFacebookAdAccountPlaceholderTitle: "No account connected",
		EmptySectionPlaceholderSubHead: "Add a new record to make it look prettier",
		EmptySectionPlaceholderTitle: "The section has no records",
		FilteredEmptySectionPlaceholderSubHead: "Clear the filter or change its conditions",
		FilteredEmptySectionPlaceholderTitle: "There are no records matching the filter criteria",
		HelpTabContainer_caption: "Help",
		HelpTabContainerFlexContainerDescriptionLabel_caption: "",
		HelpTabContainerFlexContainerMainLabel_caption: "Ad campaigns in Creatio",
		ImageInput_FacebookImage_label: "Image to upload",
		ImpressionsChartWidget_series_1: "Google",
		ImpressionsChartWidget_title: "Impression dynamics",
		ImpressionsIndicatorWidget_template: "{0}",
		ImpressionsIndicatorWidget_title: "Impressions",
		Label_55l5g18_caption: "",
		Label_670ovdf_caption: "",
		Label_Help_caption: "Help",
		ListActionButton_caption: "Actions",
		ListTitleCaption: "List title",
		MenuItem_ExcelExport_caption: "Export to Excel",
		MenuItem_ExportToExel_caption: "Export to Excel",
		MenuItem_ImportFromExel_caption: "Excel",
		MenuItem_StartSync_caption: "Start sync",
		OpenLandingDesignerCaption: "Web forms and pages",
		PDS_AdAccountCurrency: "Currency",
		PDS_CampaignName: "Name",
		PDS_Clicks: "Clicks",
		PDS_CPC: "CPC",
		PDS_CPM: "CPM",
		PDS_CTR: "CTR, %",
		PDS_Impressions: "Impressions",
		PDS_Platform: "Platform",
		PDS_PrimaryAmountSpent: "Amount spent",
		PDS_Status: "Status",
		SearchFilter_placeholder: "Search",
		TabContainer_AmountSpent_caption: "Amount spent",
		TabContainer_Clicks_caption: "Clicks",
		TabContainer_Impressions_caption: "Impressions",
		PDS_AmountSpent: "Amount spent",
		ImpressionsChartWidget_series_0: "Facebook",
		HelpTabContainerFlexContainerDescriptionLabel3_caption: "Creatio imports data from Google Ads and Facebook Ads daily out of the box.",
		HelpTabContainerFlexContainerDescriptionLabel2_caption: "The key ad performance metrics, such as the total number of contacts and cost per contact, are calculated based on the UTM parameters specified for your ad campaigns in the ad account. ",
		HelpTabContainerFlexContainerDescriptionLabel1_caption: "Use Ad campaigns, to analyze the effectiveness of your campaigns from Google Ads, Facebook, and other advertising services in single place, as well as closely monitor the impact of your ad spending on conversion."
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});