define("AdCampaign_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		ContactsIndicatorWidget_title: "Contacts",
		ContactsIndicatorWidget_template: "{0}",
		DataGrid_DailyInsightsListDS_CostPerContact: "Cost per Contact",
		DataGrid_DailyInsightsListDS_Contacts: "Contacts",
		DataGrid_DailyInsightsListDS_CostPerSubmission: "Cost per Submission",
		DataGrid_DailyInsightsListDS_Submissions: "Submissions",
		AmountSpentChartWidget_series_0: "Clicks",
		AmountSpentChartWidget_series_1: "Amount spent",
		AmountSpentChartWidget_title: "Amount spent dynamics",
		AmountSpentIndicatorWidget_template: "{0}",
		AmountSpentIndicatorWidget_title: "Amount spent",
		AmountSpentTab_caption: "Amount spent",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		ClicksIndicatorWidget_template: "{0}",
		ClicksIndicatorWidget_title: "Clicks",
		CloseButton: "Close",
		DailyInsightsExportDataButton_caption: "Export to Excel",
		DailyInsightsListLabel_caption: "Daily insights",
		DailyInsightsListSettingsButton_caption: "Actions",
		DailyInsightsStartSyncButton_caption: "Start sync",
		DataGrid_DailyInsightsListDS_Clicks: "Clicks",
		DataGrid_DailyInsightsListDS_CPC: "CPC",
		DataGrid_DailyInsightsListDS_CPM: "CPM",
		DataGrid_DailyInsightsListDS_CTR: "CTR, %",
		DataGrid_DailyInsightsListDS_DataRangeDate: "Date",
		DataGrid_DailyInsightsListDS_Impressions: "Impressions",
		DataGrid_DailyInsightsListDS_PrimaryAmountSpent: "Amount spent",
		DateRangeQuickFilter_config_caption: "Data range",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "General information",
		ImageInput_FacebookImage_label: "Image to upload",
		ImageInput_GoogleImage_label: "Image to upload",
		ImpressionsIndicatorWidget_template: "{0}",
		ImpressionsIndicatorWidget_title: "Impressions",
		NewRecord: "New record",
		Record: "Record",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});