define("AutoGeneratedPageUserTaskPropertiesPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		RecommendationLabelCaption: "To whom should the page be shown?",
		OwnerIdCaption: "Owner",
		TitleCaption: "Page title",
		ButtonsCaption: "Buttons",
		ItemsCaption: "Page Items",
		EntitySchemaContainerUIdCaption: "Which record to connect the page to?",
		EntityIdCaption: "Record of connected object",
		NotesMenuItemCaption: "Notes",
		ItemFolderMenuItemCaption: "Item block",
		TextMenuItemCaption: "Text field",
		SelectionMenuItemCaption: "Selection field",
		BooleanMenuItemCaption: "Boolean",
		DateTimeMenuItemCaption: "Date/time",
		IntegerMenuItemCaption: "Integer",
		DecimalMenuItemCaption: "Decimal",
		MoveUpMenuItemCaption: "Move up",
		MoveDownMenuItemCaption: "Move down",
		EntitySchemaUIdCaption: "Connected object",
		ActivityLinksCaption: "Connected to",
		AddParameterButtonCaption: "Add parameter",
		AfterActivitySaveScriptCaption: "After Activity Saved",
		CaptionCaption: "Title",
		ChangePageSchemaButtonCaption: "Change",
		ChangeSchemaWarningMessage: "Are you sure you want to change element schema? All parameters will be lost.",
		CloseButtonCaption: "Close",
		CurrentUserContactDisplayValue: "[#System variable.Current user contact#]",
		DaysCaption: "days",
		DeleteMenuItemCaption: "Delete",
		DescriptionCaption: "Description",
		DuplicateNameMessage: "Element with this code already exists.",
		DuplicateParameterNameMessage: "Parameter with this code already exists.",
		DurationCaption: "Planned duration",
		EditMenuItemCaption: "Edit",
		ElementPropertyNotFoundExceptionMessage: "Property \u0027{0}\u0027 not found in item \u0027{1}\u0027",
		EmptyParametersMessage: "Element has no parameters",
		ExtendedModeCaption: "Advanced mode",
		HoursCaption: "hours",
		IgnoreMultiInstanceErrorsCaption: "Continue execution on errors",
		InavalidMappingColumn: "Invalid formula",
		InformationOnStepCaption: "User hints",
		IsLoggingCaption: "Enable logging",
		MainTabInformationText: "Enter the main parameters for the task",
		MappingPlaceholderCaption: "Select value",
		MinutesCaption: "minutes",
		MonthsCaption: "months",
		MultiInstanceExecutionModeCaption: "Execution mode",
		NameCaption: "Code",
		NextTabButtonCaption: "Next \u003E",
		OwnerCaption: "Owner",
		OwnerRegionCaption: "Who performs the task?",
		ParametersTabCaption: "Parameters",
		PrimaryModeCaption: "Primary mode",
		ProcessInformationText: "Displays a custom page that is automatically generated based on the process element properties. You can specify which custom fields and buttons a custom page will contain. Perfect for creating custom step-by-step Wizards and forms. \u003Ca href=\u0022#\u0022 data-context-help-code=\u0022AutoGeneratedPageUserTaskPropertiesPage\u0022 \u003ERead more...\u003C/a\u003E",
		ProcessSchemaParameterEditPageCaption: "Insert parameter",
		RecepientTip: "Specify the email address of the recipient. You can select a specific email address or define it based on information from other process items.",
		RecommendationCaption: "Recommendation to user",
		RemindBeforeCaption: "Remind in",
		SaveButtonCaption: "Save",
		SchemaAddedMessage: "The \u0022{0}\u0022 has been added. Do you wish to select it in the \u0022{1}\u0022 element?",
		SchemaOutdatedMessage: "The \u0022{0}\u0022 page has been modified. Do you wish to update the parameters of the \u0022{1}\u0022 element?",
		SerializeToDBCaption: "Serialize in DB",
		SettingsButtonCaption: "Set",
		SettingsTabCaption: "Settings",
		ShowExecutionPageCaption: "Show page automatically",
		ShowInSchedulerCaption: "Show in calendar",
		StartInCaption: "Start in",
		TaskParametersTabInformationText: "Enter the temporary parameters for the task",
		UseBackgroundModeCaption: "Run following elements in the background",
		WeeksCaption: "weeks",
		WrongNameMessage: "Invalid value. Use symbols: a-z, A-Z, 0-9. \u003C/br\u003E Symbol: 0-9 cannot be first."
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {
		BlackToolsButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "BlackToolsButtonImage",
				hash: "1e35a244fbf576117229fbd866db69ac",
				resourceItemExtension: ".png"
			}
		},
		FieldsGroupTypeImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "FieldsGroupTypeImage",
				hash: "9b17d05932b29d0a8b7830fec7b79263",
				resourceItemExtension: ".svg"
			}
		},
		CommentTypeImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "CommentTypeImage",
				hash: "42a0790b77a51d8b66fddc69f260554b",
				resourceItemExtension: ".svg"
			}
		},
		TaskParameters: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "TaskParameters",
				hash: "19d7d306baa80e789137978ca4233569",
				resourceItemExtension: ".png"
			}
		},
		TaskParameterssSelected: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "TaskParameterssSelected",
				hash: "19d7d306baa80e789137978ca4233569",
				resourceItemExtension: ".png"
			}
		},
		Main: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "Main",
				hash: "a725a4237d24f3d9d5343be3d6717477",
				resourceItemExtension: ".png"
			}
		},
		MainSelected: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "MainSelected",
				hash: "a725a4237d24f3d9d5343be3d6717477",
				resourceItemExtension: ".png"
			}
		},
		CloseButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "CloseButtonImage",
				hash: "c5d6edb4bb180f8b30301d3dca7a12d8",
				resourceItemExtension: ".svg"
			}
		},
		ToolsButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "ToolsButtonImage",
				hash: "67b9187f776eb0c57c20bd86b63d4efc",
				resourceItemExtension: ".svg"
			}
		},
		InfoButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "InfoButtonImage",
				hash: "f67a1328d14dbc7091cc94589d7d2148",
				resourceItemExtension: ".svg"
			}
		},
		AddButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "AddButtonImage",
				hash: "7bc1980b519205382d39ea022bd498f8",
				resourceItemExtension: ".svg"
			}
		},
		AddParameterButton: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "AddParameterButton",
				hash: "a74df1a7d753e6067ab248949eb47d97",
				resourceItemExtension: ".png"
			}
		},
		ParameterEditToolsButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "ParameterEditToolsButtonImage",
				hash: "df03c3177a972b7f3b6987430f988ca3",
				resourceItemExtension: ".svg"
			}
		}
	};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});