define("AutoGeneratedPageUserTaskButtonViewModelResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		ButtonStyleDefaultCaption: "",
		ButtonStyleGreenCaption: "",
		ButtonStyleRedCaption: "",
		ButtonStyleBlueCaption: "",
		ButtonStyleGrayCaption: "",
		ButtonStyleTransparentCaption: ""
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});