define("AutoGeneratedPageUserTaskButtonMiniEditPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		NameCaption: "Caption",
		CodeCaption: "Code",
		StyleCaption: "Style",
		GenerateSignalCaption: "Generate signal",
		IsEnabledCaption: "Active",
		PerformValidationCaption: "Performs value validation"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});