define("AutoGeneratedPageUserTaskElementMiniEditPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		CaptionCaption: "Title",
		NameCaption: "Code",
		TextCaption: "Text",
		IsMultilineCaption: "Is multiline",
		IsRequiredCaption: "Required",
		CanBeMinimizedCaption: "Can be minimized",
		MinimizedCaption: "Minimized",
		DataSourceCaption: "Data source",
		ControlDataValueTypeCaption: "View",
		DateTimeFormatCaption: "Date time format",
		ValueCaption: "Value"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});