define("BulkEmailResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		BulkEmailCaption: "Email",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		ProcessListenersCaption: "Active processes",
		NameCaption: "Name",
		OwnerCaption: "Owner",
		TypeCaption: "Email type",
		StatusCaption: "Status",
		StartDateCaption: "Start",
		SenderNameCaption: "Sender\u0027s name",
		SenderEmailCaption: "Sender\u0027s email",
		SendStartDateCaption: "Started on",
		SendDueDateCaption: "Finished on",
		ClicksCaption: "Click rate, %",
		OpensCaption: "Open rate, %",
		SoftBounceCaption: "Soft Bounce, %",
		HardBounceCaption: "Hard Bounce, %",
		UnsubscribeCaption: "Unsubscribe rate, %",
		SpamCaption: "Spam rate, %",
		ClicksCountCaption: "Number of clicks",
		OpensCountCaption: "No. of opens",
		SoftBounceCountCaption: "No. of \u0022Soft bounce\u0022",
		HardBounceCountCaption: "No. of \u0022Hard bounce\u0022",
		UnsubscribeCountCaption: "No. of unsubscribes",
		SpamCountCaption: "No. of spam complaints",
		RecipientCountCaption: "Recipients",
		LastActualizeDateCaption: "Last updated on",
		TemplateSubjectCaption: "Subject",
		TemplateBodyCaption: "Template text",
		DeliveredCountCaption: "Delivered",
		NotDeliveredCountCaption: "Not delivered",
		InQueueCountCaption: "Queued",
		CanceledCountCaption: "No. of cancels",
		BlankEmailCountCaption: "Blank email",
		IncorrectEmailCountCaption: "Incorrect email",
		UnreachableEmailCountCaption: "Unreachable email",
		DoNotUseEmailCountCaption: "Do not use email",
		UnsubscribedByTypeCountCaption: "Unsubscribed by email type",
		DuplicateEmailCountCaption: "Duplicate email",
		RejectedCountCaption: "No. of rejects",
		CommonErrorCountCaption: "No. of general request errors",
		InvalidAddresseeCountCaption: "No. of invalid email addresses",
		PercentWeightCaption: "PercentWeight",
		PercentActiveWeightCaption: "PercentActiveWeight",
		PercentInactiveWeightCaption: "PercentInactiveWeight",
		SendCountCaption: "Sent count",
		CommunicationLimitCountCaption: "Cancelled (communication limit)",
		UtmSourceCaption: "utm_source",
		UtmMediumCaption: "utm_medium",
		UtmCampaignCaption: "utm_campaign",
		UtmTermCaption: "utm_term",
		UtmContentCaption: "utm_content",
		DomainsCaption: "List of domains",
		UseUtmCaption: "Use UTM tracking codes",
		StatisticDateCaption: "StatisticDate",
		ResponseProcessingCompletedCaption: "Click handling complete",
		CategoryCaption: "Category",
		LaunchOptionCaption: "Start mode",
		TemplateConfigCaption: "Template config",
		DeliveryErrorCaption: "Delivery errors count",
		IsSystemEmailCaption: "System email",
		TemplateNotFoundCountCaption: "Template not found",
		SendersDomainNotVerifiedCountCaption: "Sender\u0027s domain is not verified",
		SendersNameNotValidCountCaption: "Sender\u0027s name is not valid",
		AudienceSchemaCaption: "Bulk email audience schema",
		IsAudienceInitedCaption: "Is audience initialized",
		ThrottlingModeCaption: "Throttling mode",
		PriorityCaption: "Priority",
		ExpirationDateCaption: "Expiration date",
		BusinessTimeEndCaption: "To",
		BusinessTimeStartCaption: "From",
		DeliveryScheduleDaysCaption: "Delivery schedule days",
		DeliveryScheduleCaption: "Delivery schedule",
		ThrottlingQueueCaption: "Throttling queue",
		ExpiredCountCaption: "No. of \u0022Stopped (time to send expired)\u0022",
		TimeZoneCaption: "Time zone",
		StoppedSummaryCountCaption: "No. of \u0022Stopped (manually)\u0022",
		StoppedManuallyCountCaption: "No. of \u0022Stopped (manually)\u0022",
		StoppedInProviderCountCaption: "No. of \u0022Stopped (manually)\u0022 (provider)",
		ExpiredSummaryCountCaption: "No. of \u0022Stopped (time to send expired)\u0022 (creatio)",
		ExpiredInProviderCountCaption: "No. of \u0022Stopped (time to send expired)\u0022 (provider)",
		DelayBetweenEmailCaption: "Delay between emails",
		DailyLimitCaption: "Daily limit",
		ProviderNameCaption: "Email Service Provider",
		NotesCaption: "Notes",
		CampaignCaption: "Campaign",
		SplitTestCaption: "Split test",
		SegmentsStatusCaption: "List of contacts"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});