define("CampaignDiagramPropertyConnectorPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		EmptyPageCaption: "No item selected.\n\nPlease select an item on the campaign workflow to see its properties.",
		ElementTypeName: "Transition",
		PageConnectorIconId: "F42A059A-2F51-4882-9825-7BE9002DA1EB",
		PageRouteCaption: "Transition",
		DayTransitionCountRadioCaption: "Go to in (days)",
		DateTransitionRadioCaption: "Go to the next step immediately",
		FiltersContainerCaption: "Transition condition",
		AutoGeneratedCaptionPattern: "{0} days",
		EventInfoCaption: "The participants will go to the next step {0}. Time of the next step can be changed by resetting the event start date.",
		EmptyEventInfoCaption: "The next step will start according to the event start date. Connect the next step to a record from the Events section.",
		EmptyEmailInfoCaption: "The next step will start according to the email properties. Connect the next step to a record from the Emails section.",
		TriggerredEmailImmediateInfoCaption: "The next email will be sent instantly after a participant registers via the landing. You can change the sending method on the Email page.",
		TriggerredEmailScheduledInfoCaption: "The next email will be sent in the time period set. You can change the sending method on the Email page.",
		MassMailingEmailInfoCaption: "The next bulk email will be sent on {0}. You can set the sending time on the email page.",
		DayTransitionCountCaption: "Go to in, days ",
		CampaignPeriodDayCaption: "Days ",
		CampaignPeriodTimeCaption: "After",
		FiltersTimeContainerCaption: "When to go to the next step",
		SpecifiedTimeCaption: "within a few days",
		FromCampaignCaption: "during a day",
		InstantlyCaption: "instantly",
		StartDateCaption: "Time",
		LandingInfoCaption: "Contacts will be moved to the \u0027Landing\u0027 step, once they submit a web form. Additionally you can specify responses that will also transition contacts to the next step.",
		URLLabel: "URL"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {
		InfoImage: {
			source: 3,
			params: {
				schemaName: "CampaignDiagramPropertyConnectorPage",
				resourceItemName: "InfoImage",
				hash: "6ff5d6ce982448c1ed328c95a246a593",
				resourceItemExtension: ".png"
			}
		}
	};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});