define("CaseResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		CaseCaption: "Case",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		ProcessListenersCaption: "Active processes",
		NumberCaption: "Number",
		RegisteredOnCaption: "Registration date",
		SubjectCaption: "Subject",
		SymptomsCaption: "Description",
		OwnerCaption: "Assignee",
		ResponseDateCaption: "Response time",
		SolutionDateCaption: "Resolution time",
		StatusCaption: "Status",
		NotesCaption: "Notes",
		PriorityCaption: "Priority",
		OriginCaption: "Source",
		AccountCaption: "Account",
		ContactCaption: "Contact",
		GroupCaption: "Assignees group",
		RespondedOnCaption: "Actual response time",
		SolutionProvidedOnCaption: "Actual resolution time",
		ClosureDateCaption: "Closed on",
		ClosureCodeCaption: "Reason for closing",
		SolutionCaption: "Resolution",
		SatisfactionLevelCaption: "Satisfaction level",
		CategoryCaption: "Category",
		ResponseOverdueCaption: "Overdue response",
		SolutionOverdueCaption: "Overdue resolution",
		SatisfactionLevelCommentCaption: "Feedback notes",
		SolutionRemainsCaption: "Remaining until resolution time",
		ServicePactCaption: "SLA",
		ServiceItemCaption: "Service",
		ProblemCaption: "Problem",
		SupportLevelCaption: "Support line",
		SolvedOnSupportLevelCaption: "Resolved by",
		ParentCaseCaption: "Parent case",
		ChangeCaption: "Change",
		ServiceCategoryCaption: "Service category",
		FirstSolutionProvidedOnCaption: "First resolution time",
		HolderCaption: "Owner",
		ProcessingTimeUnitCaption: "Processing time unit",
		ProcessingTimeUnitValueCaption: "Processing time unit value",
		ConfItemCaption: "Configuration item",
		ParentActivityCaption: "Parent activity"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});