define("Cases_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		CustomerProfileTabContainerHeaderLabel_caption: "Customer profile",
		CustomerProfileTabContainer_caption: "Customer profile",
		addRecord_myjkaqn_caption: "Add new",
		addRecord_tv82bbh_caption: "Add new",
		addRecord_juptj26_caption: "Add new",
		AccountInfoLabel_caption: "Account info",
		Label_59nue7x_caption: "Account info",
		ActivitiesAddButton_caption: "New",
		ActivitiesExpansionPanel_title: "Activities",
		ActivitiesExportDataButton_caption: "Export to Excel",
		ActivitiesImportDataButton_caption: "Data import",
		ActivitiesRefreshButton_caption: "Refresh",
		ActivitiesSearchFilter_placeholder: "Search",
		ActivitiesSettingsButton_caption: "Actions",
		addRecord_1fg0dsp_caption: "Add new",
		addRecord_29owxq7_caption: "Add new",
		addRecord_iifryop_caption: "Add new",
		addRecord_ij355ic_caption: "Add new",
		addRecord_khhzgc9_caption: "Add new",
		addRecord_kp67ryq_caption: "Add new",
		addRecord_n4mem4y_caption: "Add new",
		addRecord_rcyw9m2_caption: "Add new",
		addRecord_sai31tf_caption: "Add new",
		addRecord_v70ts6s_caption: "Add new",
		AssignToMeButton_caption: "Assign to me",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		Button_nlty3vs_caption: "Refresh",
		Button_vd2uljn_caption: "Actions",
		CancelButton: "Cancel",
		CaseGeneralInfoTab_caption: "General Info",
		CaseInfoLabel_caption: "Case info",
		CaseLifecycleExpansionPanel_title: "Case lifecycle",
		CaseLifecycleExportDataButton_caption: "Export to Excel",
		CaseLifecycleImportDataButton_caption: "Data import",
		CaseLifecycleRefreshButton_caption: "Refresh",
		CaseLifecycleSearchFilter_placeholder: "Search",
		CaseLifecycleSettingsButton_caption: "Actions",
		CloseButton: "Close",
		ClosureAndFeedbackTab_caption: "Closure and feedback",
		DefaultHeaderCaption: "Page title",
		EscalateButton_caption: "Escalate",
		ExpansionPanel_5s964cq_title: "Case lifecycle",
		ExpansionPanel_hiqjo9r_title: "Expansion panel",
		ExpansionPanel_hxfe0bg_title: "Terms",
		ExpansionPanel_n8yfhhj_title: "Expansion panel",
		FeedbackExpansionPanel_title: "Feedback",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "Conversation",
		GridDetailAddBtn_x1oxk5t_caption: "New",
		GridDetailExportDataBtn_8u5sych_caption: "Export to Excel",
		GridDetailExportDataBtn_bvdq6jt_caption: "Export to Excel",
		GridDetailExportDataBtn_hid5b3d_caption: "Export to Excel",
		GridDetailExportDataBtn_mj5o5wg_caption: "Export to Excel",
		GridDetailImportDataBtn_c1kmyhh_caption: "Data import",
		GridDetailImportDataBtn_hfokqzj_caption: "Data import",
		GridDetailImportDataBtn_lrlkg9u_caption: "Data import",
		GridDetailImportDataBtn_rojvg62_caption: "Data import",
		KnowledgeBaseArticlesAddButton_caption: "New",
		KnowledgeBaseArticlesExpansionPanel_title: "Knowledge base articles",
		KnowledgeBaseArticlesExportDataButton_caption: "Export to Excel",
		KnowledgeBaseArticlesImportDataButton_caption: "Data import",
		KnowledgeBaseArticlesList_89c4504d: "Number of views",
		KnowledgeBaseArticlesRefreshButton_caption: "Refresh",
		KnowledgeBaseArticlesSearchFilter_placeholder: "Search",
		KnowledgeBaseArticlesSettingsButton_caption: "Actions",
		MenuItem_db9ki1a_caption: "Menu item",
		MenuItem_j912r5k_caption: "Export to Excel",
		MenuItem_sc4ga0v_caption: "Data import",
		NewRecord: "New record",
		NumberOfReopeningsIndicatorWidget_template: "{0}",
		NumberOfReopeningsIndicatorWidget_title: "Number of reopenings",
		PerformanceTab_caption: "Performance",
		ReclassifyButton_caption: "Reclassify",
		Record: "Record",
		ResolutionMainTimer_negativeTextValue: "[#timer#] overdue",
		ResolutionMainTimer_positiveTextValue: "[#timer#]",
		ResolutionTimer_negativeTextValue: "Delay: [#timer#]",
		ResolutionTimer_positiveTextValue: "Remaining: [#timer#]",
		ResponseTimer_negativeTextValue: "Delay: [#timer#]",
		ResponseTimer_positiveTextValue: "Remaining: [#timer#]",
		SatisfactionLevel_tooltip: "The CSAT score that the customer leaves on the \u201Cthank-you\u201D page",
		SatisfactionLevelComment_tooltip: "The comment that the customer leaves on the \u201Cthank-you\u201D page",
		SaveButton: "Save",
		SearchFilter_j01a0xl_placeholder: "Search",
		SetRecordRightsButtonCaption: "Set up access rights",
		SubordinateCasesAddButton_caption: "New",
		SubordinateCasesExpansionPanel_title: "Subordinate cases",
		SubordinateCasesExportDataButton_caption: "Export to Excel",
		SubordinateCasesImportDataButton_caption: "Data import",
		SubordinateCasesRefreshButton_caption: "Refresh",
		SubordinateCasesSearchFilter_placeholder: "Search",
		SubordinateCasesSettingsButton_caption: "Actions",
		TermsExpansionPanel_title: "Terms",
		TermsLabel_caption: "Terms",
		TimeInProgressIndicatorWidget_template: "{0}",
		TimeInProgressIndicatorWidget_title: "Time in progress, hours",
		TimeLeftForResolutionLabel_caption: "Time left for resolution",
		Timeline_4gfwh7t_caption: "Timeline",
		Timeline_4gfwh7t_label: "Timeline",
		Timeline_caption: "Timeline",
		Timeline_label: "Timeline",
		Timeline_v0cacsv_caption: "Timeline",
		Timeline_v0cacsv_label: "Timeline",
		Timeline_vqv4ozm_caption: "Timeline",
		Timeline_vqv4ozm_label: "Timeline",
		TimeOnSupportLinesChartWidget_series_0: "Case Lifecycle",
		TimeOnSupportLinesChartWidget_title: "Time on support lines, hours",
		TimeOnSupportLinesChartWidget_xAxis: "",
		TimeOnSupportLinesChartWidget_yAxis: "hours",
		TimeToFirstResponseIndicatorWidget_template: "{0}",
		TimeToFirstResponseIndicatorWidget_title: "Time to first response, hours"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});