define("ContactResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		ContactCaption: "Contact",
		IdCaption: "Id",
		NameCaption: "Full name",
		OwnerCaption: "Owner",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		ProcessListenersCaption: "Active processes",
		DearCaption: "Recipient\u0027s name",
		SalutationTypeCaption: "Title",
		GenderCaption: "Gender",
		AccountCaption: "Account",
		DecisionRoleCaption: "Role",
		TypeCaption: "Type",
		JobCaption: "Job title",
		JobTitleCaption: "Full job title",
		DepartmentCaption: "Department",
		BirthDateCaption: "Birth date",
		PhoneCaption: "Business phone",
		MobilePhoneCaption: "Mobile phone",
		HomePhoneCaption: "Home phone",
		SkypeCaption: "Skype",
		EmailCaption: "Email",
		AddressTypeCaption: "Address type",
		AddressCaption: "Address",
		CityCaption: "City",
		RegionCaption: "State/province",
		ZipCaption: "ZIP/postal code",
		CountryCaption: "Country",
		DoNotUseEmailCaption: "Do not use email",
		DoNotUseCallCaption: "Do not use phone",
		DoNotUseFaxCaption: "Do not use fax",
		DoNotUseSmsCaption: "Do not use SMS",
		DoNotUseMailCaption: "Do not use mail",
		NotesCaption: "Notes",
		FacebookCaption: "Facebook",
		LinkedInCaption: "LinkedIn",
		TwitterCaption: "Twitter",
		FacebookIdCaption: "FacebookId",
		LinkedInIdCaption: "LinkedInId",
		TwitterIdCaption: "TwitterId",
		ContactPhotoCaption: "ContactPhoto",
		TwitterAFDACaption: "Twitter Account for Data Access",
		FacebookAFDACaption: "Facebook Account for Data Access",
		LinkedInAFDACaption: "LinkedIn Account for Data Access",
		PhotoCaption: "Photo",
		GPSNCaption: "GPS N",
		GPSECaption: "GPS E",
		SurnameCaption: "Last name",
		GivenNameCaption: "First name",
		MiddleNameCaption: "Middle name",
		ConfirmedCaption: "Confirmed",
		IsNonActualEmailCaption: "Invalid email",
		CompletenessCaption: "Data entry compliance",
		LanguageCaption: "Preferred language",
		AgeCaption: "Age",
		IsEmailConfirmedCaption: "IsEmailConfirmed",
		AdCampaignCaption: "Ad campaign",
		CustomerNeedCaption: "Customer need",
		ChannelCaption: "Channel",
		SourceCaption: "Source",
		RegisterMethodCaption: "Registration method",
		LeadConversionScoreCaption: "Lead conversion score"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});