define("Contacts_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		RecommendedProductSearchFilter_placeholder: "Search",
		GridDetailImportDataBtn_f26nmj3_caption: "Data import",
		RecommendedProductExportDataButton_caption: "Export to Excel",
		RecommendedProductSettingsButton_caption: "Actions",
		RecommendedProductRefreshButton_caption: "Refresh",
		GridDetailAddBtn_8hnptnp_caption: "New",
		RecommendedProductExpansionPanel_title: "Recommended products",
		OpportunitySearchFilter_placeholder: "Search",
		OpportunityImportDataButton_caption: "Data import",
		OpportunityExportDataButton_caption: "Export to Excel",
		OpportunitySettingsButton_caption: "Actions",
		OpportunityRefreshButton_caption: "Refresh",
		OpportunityAddButton_caption: "New",
		OpportunityExpansionPanel_title: "Opportunities",
		Account_placeholder: "Select account",
		AccountCategory_ariaLabel: "Dropdown",
		AccountCategory_label: "Dropdown",
		AccountIndustry_ariaLabel: "Dropdown",
		AccountIndustry_label: "Dropdown",
		AccountInfoExpansionPanel_title: "Account info",
		addRecord_e9kbl5o_caption: "Add new",
		addRecord_oz5z1xx_caption: "Add new",
		AddressAddButton_caption: "New",
		AddressExpansionPanel_title: "Addresses",
		AddressExportDataButton_caption: "Export to Excel",
		AddressImportDataButton_caption: "Data import",
		AddressRefreshButton_caption: "Refresh",
		AddressSearchFilter_placeholder: "Search",
		AddressSettingsButton_caption: "Actions",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CareerAddButton_caption: "New",
		CareerExpansionPanel_title: "Job experience",
		CareerExportDataButton_caption: "Export to Excel",
		CareerImportDataButton_caption: "Data import",
		CareerRefreshButton_caption: "Refresh",
		CareerSearchFilter_placeholder: "Search",
		CareerSettingsButton_caption: "Actions",
		CloseButton: "Close",
		Dear_placeholder: "Enter legal name",
		DefaultHeaderCaption: "Page title",
		Email_placeholder: "Enter email",
		FeedTabContainerCaption: "Feed",
		Gender_placeholder: "Select gender",
		GeneralInfoTab_caption: "Contact info",
		JobTitle_placeholder: "Enter job title",
		Language_placeholder: "Select language",
		MobilePhone_placeholder: "Enter phone number",
		NewRecord: "New record",
		Owner_placeholder: "Select owner",
		PageTitle_caption: "Page title",
		Record: "Record",
		SalutationType_placeholder: "Select title",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights",
		Timeline_caption: "Timeline",
		Timeline_label: "Timeline",
		TimelineTab_caption: "Timeline",
		Type_placeholder: "Select contact type",
		BulkEmailList_59f54b50: "Sent date",
		BulkEmailList_d96e6f8c: "Type",
		BulkEmailSearchFilter_placeholder: "Search",
		GridDetailImportDataBtn_ay7t1nq_caption: "Data import",
		BulkEmailExportDataButton_caption: "Export to Excel",
		BulkEmailSettingsButton_caption: "Actions",
		BulkEmailRefreshButton_caption: "Refresh",
		GridDetailAddBtn_9p9pxsz_caption: "New",
		BulkEmailExpansionPanel_title: "Bulk emails",
		ServiceAgreementsListDS_ServicePact: "Service agreement",
		ContactCommunicationOptionsAddButton_caption: "Add communication option",
		Source_placeholder: "Select source",
		Channel_placeholder: "Select channel",
		RegisterMethod_placeholder: "Select registration method",
		CustomerNeed_placeholder: "Select customer need",
		addRecord_lxl6b00_caption: "Add new",
		addRecord_d871xfp_caption: "Add new",
		addRecord_peavqxg_caption: "Add new",
		addRecord_mul04nj_caption: "Add new",
		GridDetailSearchFilter_m3w49bc_placeholder: "Search",
		GridDetailImportDataBtn_uknb3rf_caption: "Data import",
		GridDetailExportDataBtn_rls9rem_caption: "Export to Excel",
		GridDetailSettingsBtn_icmycs2_caption: "Actions",
		GridDetailRefreshBtn_zda9av2_caption: "Refresh",
		GridDetailAddBtn_2djs4b4_caption: "New",
		ExpansionPanel_waeo36h_title: "MQL/SQL",
		GridDetailSearchFilter_xaaj1yc_placeholder: "Search",
		GridDetailImportDataBtn_lyt0jdm_caption: "Data import",
		GridDetailExportDataBtn_64g7yfo_caption: "Export to Excel",
		GridDetailSettingsBtn_g626uxc_caption: "Actions",
		GridDetailRefreshBtn_ypobw9p_caption: "Refresh",
		GridDetailAddBtn_vuv87zn_caption: "New",
		ExpansionPanel_wnddm9x_title: "MQL/SQL",
		Button_8lva7d5_caption: "Create lead",
		ExpansionPanel_vnm6t7m_title: "Submitted forms",
		MenuItem_tc2qcwu_caption: "Data import",
		MenuItem_smyltlp_caption: "Export to Excel",
		Button_srxtvyo_caption: "Actions",
		Button_uld37ti_caption: "Refresh",
		SearchFilter_dyiu0p0_placeholder: "Search",
		addRecord_0d8td67_caption: "Add new",
		addRecord_2kkc2vg_caption: "Add new",
		addRecord_cjzgd0e_caption: "Add new",
		addRecord_j18vog1_caption: "Add new",
		ComboBox_268yz1f_placeholder: "Select source",
		ComboBox_3zub1m3_label: "Select",
		ComboBox_3zub1m3_placeholder: "Select channel",
		ExpansionPanel_1re2q9h_title: "Submitted forms",
		GridDetailAddBtn_wzj2id8_caption: "New",
		GridDetailExportDataBtn_iefo8tm_caption: "Export to Excel",
		GridDetailImportDataBtn_czhqpwi_caption: "Data import",
		GridDetailRefreshBtn_k5ozk6j_caption: "Refresh",
		GridDetailSearchFilter_769sr56_placeholder: "Search",
		GridDetailSettingsBtn_weylxjf_caption: "Actions",
		LeadConversionScore_tooltip: "The score indicates the probability of creating a Lead associated with the Contact. The value is calculated with the ML model",
		Slider_nqxtwy2_label: "e",
		SalesTab_caption: "Sales",
		LeadSearchFilter_placeholder: "Search",
		LeadImportDataButton_caption: "Data import",
		LeadExportDataButton_caption: "Export to Excel",
		LeadSettingsButton_caption: "Actions",
		LeadRefreshButton_caption: "Refresh",
		LeadAddButton_caption: "New",
		LeadExpansionPanel_title: "MQL/SQL",
		OrderSearchFilter_placeholder: "Search",
		OrderImportDataButton_caption: "Data import",
		OrderExportDataButton_caption: "Export to Excel",
		OrderSettingsButton_caption: "Actions",
		OrderRefreshButton_caption: "Refresh",
		OrderAddButton_caption: "New",
		OrderExpansionPanel_title: "Orders",
		MarketingTab_caption: "Marketing",
		ExpansionPanel_cl6jd1j_title: "Expanded list",
		ExpansionPanel_orushf4_title: "Expanded list",
		GridDetailAddBtn_iuanhaw_caption: "New",
		GridDetailAddBtn_us2ka4c_caption: "New",
		GridDetailAddBtn_z5wul71_caption: "New",
		GridDetailExportDataBtn_4fz0vrd_caption: "Export to Excel",
		GridDetailExportDataBtn_qmzntqd_caption: "Export to Excel",
		GridDetailImportDataBtn_fcfuqv2_caption: "Data import",
		GridDetailImportDataBtn_mzilom4_caption: "Data import",
		GridDetailRefreshBtn_65ju6sm_caption: "Refresh",
		GridDetailRefreshBtn_b3l05aw_caption: "Refresh",
		GridDetailSearchFilter_elz657z_placeholder: "Search",
		GridDetailSearchFilter_hlsnoa9_placeholder: "Search",
		GridDetailSettingsBtn_guwzrkm_caption: "Actions",
		GridDetailSettingsBtn_l68p3oj_caption: "Actions",
		MenuItem_tz82vh6_caption: "Data import",
		MrktLeadAddButton_caption: "New",
		MrktLeadExpansionPanel_title: "MQL/SQL",
		MrktLeadExportDataButton_caption: "Export to Excel",
		MrktLeadImportDataButton_caption: "Data import",
		MrktLeadRefreshButton_caption: "Refresh",
		MrktLeadSearchFilter_placeholder: "Search",
		MrktLeadSettingsButton_caption: "Actions",
		SubmittedFormExpansionPanel_title: "Submitted forms",
		SubmittedFormExportDataButton_caption: "Export to Excel",
		SubmittedFormImportDataButton_caption: "Data import",
		SubmittedFormRefreshButton_caption: "Refresh",
		SubmittedFormSearchFilter_placeholder: "Search",
		SubmittedFormSettingsButton_caption: "Actions",
		WebActionExpansionPanel_title: "Web actions",
		WebActionExportDataButton_caption: "Export to Excel",
		WebActionImportDataButton_caption: "Data import",
		WebActionList_a9a6f0cb: "Start date",
		WebActionList_f312b329: "Page URL address",
		WebActionRefreshButton_caption: "Refresh",
		WebActionSearchFilter_placeholder: "Search",
		WebActionSettingsButton_caption: "Actions",
		WebSessionButton_caption: "Refresh",
		WebSessionExpansionPanel_title: "Web sessions",
		WebSessionExportDataButton_caption: "Export to Excel",
		WebSessionList_1259aaa8: "Duration, sec",
		WebSessionList_439c70ce: "City",
		WebSessionList_50a6c11c: "Start date",
		WebSessionList_bb96b5ea: "Country",
		WebSessionList_fa5fb4d8: "Actions",
		WebSessionRefreshButton_caption: "Refresh",
		WebSessionSearchFilter_placeholder: "Search",
		WebSessionSettingsButton_caption: "Actions",
		EventSearchFilter_placeholder: "Search",
		GridDetailImportDataBtn_950wnaz_caption: "Data import",
		EventExportDataButton_caption: "Export to Excel",
		EventSettingsButton_caption: "Actions",
		EventRefreshButton_caption: "Refresh",
		GridDetailAddBtn_ndfhsfl_caption: "New",
		EventExpansionPanel_title: "Events",
		TabContainer_mv41ha8_caption: "Service",
		CasesSearchFilter_placeholder: "Search",
		CasesImportDataButton_caption: "Data import",
		CasesExportDataButton_caption: "Export to Excel",
		CasesSettingsButton_caption: "Actions",
		CasesRefreshButton_caption: "Refresh",
		CasesAddButton_caption: "New",
		CasesExpansionPanel_title: "Cases",
		GridDetailSearchFilter_sj49lgw_placeholder: "Search",
		GridDetailImportDataBtn_714xipa_caption: "Data import",
		GridDetailExportDataBtn_d9kp62y_caption: "Export to Excel",
		GridDetailSettingsBtn_63wr3ah_caption: "Actions",
		GridDetailRefreshBtn_ajk754f_caption: "Refresh",
		GridDetailAddBtn_cwv991v_caption: "New",
		ExpansionPanel_5etntax_title: "Expanded list",
		ServiceTab_caption: "Service",
		ServiceAgreementsSearchFilter_placeholder: "Search",
		ServiceAgreementsImportDataButton_caption: "Data import",
		ServiceAgreementsExportDataButton_caption: "Export to Excel",
		ServiceAgreementsSettingsButton_caption: "Actions",
		ServiceAgreementsRefreshButton_caption: "Refresh",
		GridDetailAddBtn_nn4e4tv_caption: "New",
		ServiceAgreementsExpansionPanel_title: "Service agreements",
		ServiceAgreementsList_623c7fb3: "Owner",
		ServiceAgreementsList_86478300: "Status",
		ServiceAgreementsList_4f106e3b: "Title",
		ServiceAgreementsList_5f9c7ad3: "Number",
		CampaignSearchFilter_placeholder: "Search",
		GridDetailImportDataBtn_k7c9wfe_caption: "Data import",
		CampaignExportDataButton_caption: "Export to Excel",
		CampaignSettingsButton_caption: "Actions",
		CampaignRefreshButton_caption: "Refresh",
		GridDetailAddBtn_pjzbr97_caption: "New",
		CampaignExpansionPanel_title: "Campaigns",
		CampaignList_a4608c16: "Contact status",
		CampaignList_258906ba: "Campaign status"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});