define("ContentBlockResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		ContentBlockCaption: "Content block",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		ProcessListenersCaption: "Active processes",
		NameCaption: "Name",
		DescriptionCaption: "Description",
		ConfigCaption: "Content block setup",
		ImageCaption: "Image",
		IsAutoGeneratedImageCaption: "Flag that indicates image generated automatically"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});