define("Contracts_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		Owner_tooltip: "Full name of the record owner. Select the owner from the contacts registered as users in the system.",
		addRecord_jw0oh71_caption: "Add new",
		addRecord_948r1p3_caption: "Add new",
		addRecord_2425btr_caption: "Add new",
		addRecord_yizlc6v_caption: "Add new",
		SubordinateContractListAddButton_caption: "New",
		ParentContract_tooltip: "The parental agreement towards current document. Available for editing only for specifications and additional agreements. This field is editable and is completed automatically when adding records on the [Subordinate contracts] detail",
		Amount_tooltip: "Total contract amount. If the contract is created based on an order, the field becomes non-editable and is calculated as a total amount of products in the contract. The products are copied to the contract from the order. The field is editable, if the contract is not connected to an order",
		OurBankingDetails_tooltip: "Banking details of our company. The list of field values is generated based on the [Banking details] specified for our company",
		AccountBankingDetails_tooltip: "Banking details of an account. Go to the [Banking details] of the account page to add a new value",
		ContractDetailsTab_caption: "Contract details",
		ApprovalListExpansionPanel_title: "Approvals list",
		SendForApprovalButton_caption: "Send for approval",
		ApprovalsTab_caption: "Approvals",
		ApprovalListRefreshButton_caption: "Refresh",
		ProductListRefreshButton_caption: "Refresh",
		SubordinateContractListRefreshButton_caption: "Refresh",
		SubordinateContractsExpansionPanel_title: "Subordinate contracts",
		ApprovalListSearchFilter_placeholder: "Search",
		ProductListSettingsButton_caption: "Actions",
		ProductListSearchFilter_placeholder: "Search",
		ProductListAddButton_caption: "New",
		SubordinateContractListImportDataButton_caption: "Data import",
		SubordinateContractListExportDataButton_caption: "Export to Excel",
		SubordinateContractListSettingsButton_caption: "Actions",
		SubordinateContractListSearchFilter_placeholder: "Search",
		PrintButton_caption: "Print",
		ProductsExpansionPanel_title: "Products",
		ContractInfoLabel_caption: "Contract info",
		ProductsImportDataButton_caption: "Data import",
		ProductsExportDataButton_caption: "Export to Excel",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "General information",
		NewRecord: "New record",
		Record: "Record",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});