define("Documents_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		EmailInput_5qv50kb_label: "Email address",
		EmailInput_5qv50kb_caption: "Email address",
		PhoneInput_9rn9yle_label: "Phone number",
		PhoneInput_9rn9yle_caption: "Phone number",
		addRecord_8velva1_caption: "Add new",
		ComboBox_8v995zi_ariaLabel: "Dropdown",
		ComboBox_8v995zi_label: "Dropdown",
		addRecord_z9aigow_caption: "Add new",
		ComboBox_f52f1vu_ariaLabel: "Dropdown",
		ComboBox_f52f1vu_label: "Dropdown",
		WebInput_8h07mv3_label: "Web link",
		WebInput_8h07mv3_caption: "Web link",
		Label_w7xj87v_caption: "Account info",
		AccountLabel_caption: "Account info",
		addRecord_j5xiaof_caption: "Add new",
		addRecord_njngkjy_caption: "Add new",
		addRecord_q5m8gie_caption: "Add new",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "General information",
		NewRecord: "New record",
		Owner_tooltip: "Full name of the record owner. Select the owner from the contacts registered as users in the system.",
		Record: "Record",
		RelatedDocumentsAddButton_caption: "New",
		RelatedDocumentsExpansionPanel_title: "Related documents",
		RelatedDocumentsExportDataButton_caption: "Export to Excel",
		RelatedDocumentsImportDataButton_caption: "Data import",
		RelatedDocumentsListDS_DocumentB: "Number",
		RelatedDocumentsRefreshButton_caption: "Refresh",
		RelatedDocumentsSearchFilter_placeholder: "Search",
		RelatedDocumentsSettingsButton_caption: "Actions",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});