define("EmailFormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		TabContainer_2eqcl4q_caption: "General info",
		SaveButton_caption: "Reply",
		CancelButton_caption: "Cancel",
		GridDetailSearchFilter_90nxrnj_placeholder: "Search",
		GridDetailRefreshBtn_iu8up48_caption: "Refresh",
		GridDetailAddBtn_bnf7kkh_caption: "Upload",
		ExpansionPanel_ogdvdph_title: "Attachments",
		AttachmentsTabContainer_caption: "Attachments",
		Label_qh6twyb_caption: "Attachments",
		TabContainer_x9ufdpr_caption: "Attachments",
		ConnectionsTabContainer_caption: "Connections",
		FeedTabContainer_caption: "Feed",
		Label_2jzb4wj_caption: "Feed",
		TabContainer_msxap8x_caption: "Feed",
		Label_v9e0gvg_caption: "Connections",
		TabContainer_4qky7oz_caption: "Connections",
		addRecord_hi4kfnp_caption: "Add new",
		addRecord_u2ih2ms_caption: "Add new",
		addRecord_jxahw51_caption: "Add new",
		GridDetailSearchFilter_55p780w_placeholder: "Search",
		GridDetailImportDataBtn_vp5z3z6_caption: "Data import",
		GridDetailExportDataBtn_sdroz27_caption: "Export to Excel",
		GridDetailSettingsBtn_gedpuqq_caption: "Actions",
		GridDetailRefreshBtn_xpb1hrb_caption: "Refresh",
		GridDetailAddBtn_xfpniv9_caption: "New",
		ExpansionPanel_kb90i8i_title: "Known contacts in Email",
		GridDetail_jj11595DS_Role: "Email direction",
		GridDetail_jj11595DS_ParticipantJob: "Job title",
		GridDetail_jj11595DS_ParticipantAccount: "Account",
		GridDetail_jj11595DS_Participant: "Contact",
		ReplyButton_caption: "Reply/Forward",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "Message",
		NewRecord: "New record",
		Record: "Record",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});