define("ExternalCases_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		Label_cq117yc_caption: "Terms",
		Timeline_0zkfh5o_label: "Timeline",
		Timeline_0zkfh5o_caption: "Timeline",
		addRecord_94ey3ac_caption: "Add new",
		addRecord_1qnv96k_caption: "Add new",
		addRecord_hf17e9h_caption: "Add new",
		addRecord_45y6j03_caption: "Add new",
		Label_9sli4x1_caption: "Case info",
		Timer_2g724r4_negativeTextValue: "[#timer#]",
		Timer_2g724r4_positiveTextValue: "[#timer#]",
		Timer_2on1knj_negativeTextValue: "[#timer#]",
		Timer_2on1knj_positiveTextValue: "[#timer#]",
		Timer_jiecd7h_negativeTextValue: "[#timer#]",
		Timer_jiecd7h_positiveTextValue: "[#timer#]",
		ResponseTimer_negativeTextValue: "[#timer#]",
		ResponseTimer_positiveTextValue: "[#timer#]",
		Timer_vwjtvs8_label: "Timer",
		Timer_vwjtvs8_caption: "Timer",
		ResolutionTimer_negativeTextValue: "[#timer#]",
		ResolutionTimer_positiveTextValue: "[#timer#]",
		ResolutionTimer_caption: "Timer",
		ResponseTimer_caption: "Timer",
		TabContainer_k3mjo03_caption: "Tab 2",
		TabContainer_l3p6hpn_caption: "Tab 1",
		SatisfactionLevelComment_label: "What would you like to share with us?",
		addRecord_pnag3mh_caption: "Add new",
		Label_ckm678z_caption: "Feedback",
		Timer_pnfs9r2_positiveTextValue: "[#timer#]",
		Timer_pnfs9r2_negativeTextValue: "[#timer#]",
		Timer_pnfs9r2_caption: "Timer",
		Timer_zi4qy5a_positiveTextValue: "[#timer#]",
		Timer_zi4qy5a_negativeTextValue: "[#timer#]",
		Timer_zi4qy5a_caption: "Timer",
		Button_2lqb4c8_caption: "Submit feedback",
		SubmitFeedbackButton_caption: "Submit feedback",
		Timer_2ktoas2_positiveTextValue: "[#timer#]",
		Timer_2ktoas2_negativeTextValue: "[#timer#]",
		Timer_2ktoas2_caption: "Timer",
		Timer_pbyr9og_positiveTextValue: "[#timer#]",
		Timer_pbyr9og_negativeTextValue: "[#timer#]",
		Timer_pbyr9og_caption: "Timer",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "General information",
		NewRecord: "New record",
		Record: "Record",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});