define("FormulaDesignerResourcesResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		DATEADDFunctionsMenuCaption: "Add to date",
		DATEDIFFFunctionsMenuCaption: "Date difference",
		DATEPARTFunctionsMenuCaption: "Date part",
		FieldExpressionTitle: "Formula expression",
		FormulaDivisionByZero: "Position: {0}. Division by zero.",
		FormulaMaxNumberLength: "Position: {0}. Whole part of the number cannot be more than {1} characters.",
		FormulaMaxNumberPrecisionLength: "Position: {0}. Decimal part of the number cannot be more than {1} characters.",
		FormulaMissingClosingParentheses: "Position: {0}. Missing closing parenthesis.",
		FormulaMissingOpeningParentheses: "Position: {0}. Missing opening parenthesis.",
		FormulaMissingOperand: "Position: {0}. Missing operand near \u0027{1}\u0027.",
		FormulaNotSupportedOnlyColumn: "Formula expression cannot have one column. Add arithmetic operations.",
		FormulaRequired: "Formula expression cannot be empty. Add columns and arithmetic operations.",
		FormulaUnexpectedClosingParentheses: "Position: {0}. Unexpected closing parenthesis.",
		FormulaUnexpectedDecimalSeparator: "Position: {0}. Unexpected formula item \u0027{1}\u0027. The decimal separator is a \u0027.\u0027.",
		FormulaUnexpectedItem: "Position: {0}. Unexpected formula item \u0027{1}\u0027.",
		FormulaUnexpectedOpeningParentheses: "Position: {0}. Unexpected opening parenthesis.",
		FunctionDateAddDaysCaption: "AddDay",
		FunctionDateAddHoursCaption: "AddHour",
		FunctionDateAddMonthsCaption: "AddMonth",
		FunctionDateAddMinutesCaption: "AddMinute",
		FunctionDateAddQuartersCaption: "AddQuarter",
		FunctionDateAddSecondsCaption: "AddSecond",
		FunctionDateAddWeeksCaption: "AddWeek",
		FunctionDateAddYearsCaption: "AddYear",
		FunctionDateDiffDaysCaption: "DiffDay",
		FunctionDateDiffHoursCaption: "DiffHour",
		FunctionDateDiffMinutesCaption: "DiffMinute",
		FunctionDateDiffMonthsCaption: "DiffMonth",
		FunctionDateDiffQuartersCaption: "DiffQuarter",
		FunctionDateDiffSecondsCaption: "DiffSecond",
		FunctionDateDiffWeeksCaption: "DiffWeek",
		FunctionDateDiffYearsCaption: "DiffYear",
		GetDateFunctionsMenuCaption: "Current date",
		FunctionDatePartDaysCaption: "PartDay",
		FunctionDatePartDaysWeeksCaption: "PartDayWeek",
		FunctionDatePartHoursCaption: "PartHour",
		FunctionDatePartMonthsCaption: "PartMonth",
		FunctionDatePartWeeksCaption: "PartWeek",
		FunctionDatePartYearsCaption: "PartYear",
		FunctionsMenuCaption: "Function",
		OperandsMenuCaption: "Parameter",
		OperatorsMenuCaption: "Operator",
		FormulaUnsupportedBinaryOperandDataType: "Position: {0}. The operator \u0027{1}\u0027 is not valid between the specified data types.",
		FormulaInvalidFunctionArgumentsCount: "Position: {0}. Incorrect number of arguments in the \u0027{1}\u0027 function. Requires {3} argument(s), specified {2}.",
		FormulaInvalidFunctionArgumentDataType: "Position: {0}. Unexpected data type of {1} argument in the \u0027{2}\u0027 function.",
		AcademyLinkTitle: "Read more about formula ",
		AcademyLinkUrl: "https://academy.creatio.com/documents?product=administration\u0026ver=7\u0026id=2322",
		FunctionGetDateTimeCaption: "CurrentDateTime"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});