define("FormSubmitResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		FormSubmitCaption: "Submitted form",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		ProcessListenersCaption: "Active processes",
		ContactCaption: "Contact",
		FormDataCaption: "Data",
		WebFormCaption: "Web form",
		PhoneNumberCaption: "Phone number",
		EmailCaption: "Email",
		LastNameCaption: "Last name",
		FirstNameCaption: "First name",
		FullNameCaption: "Full name",
		CountryStrCaption: "Country (string)",
		CountryCaption: "Country",
		AccountIndustryStrCaption: "Industry (string)",
		AccountIndustryCaption: "Industry",
		JobTitleCaption: "Job title",
		ContactDecisionRoleStrCaption: "Role (string)",
		ContactDecisionRoleCaption: "Role",
		WorkEmailCaption: "Work email",
		AccountEmployeesNumberStrCaption: "No. of employees (string)",
		AccountEmployeesNumberCaption: "No. of employees",
		AccountCaption: "Account name",
		WebsiteCaption: "Website",
		GenderCaption: "Gender",
		TimeZoneCaption: "Time zone",
		TerritoryCaption: "Territory",
		CityStrCaption: "City (string)",
		CityCaption: "City",
		BirthDateCaption: "Birth date",
		PasswordCaption: "Password",
		LinkedInProfileUrlCaption: "LinkedIn profile",
		RegisterMethodCaption: "Registration method",
		NotesCaption: "Notes",
		SourceCaption: "Source",
		ChannelCaption: "Channel",
		UtmCampaignStrCaption: "utm_campaign",
		UtmMediumStrCaption: "utm_medium",
		UtmSourceStrCaption: "utm_source",
		ReferrerCaption: "Redirection website",
		WebFormDataCaption: "Data from web form",
		LandingPageURLCaption: "Landing page URL",
		UtmTermStrCaption: "utm_term",
		UtmContentStrCaption: "utm_content",
		CustomerNeedCaption: "Customer need",
		BulkEmailCaption: "Bulk email",
		CampaignCaption: "Campaign",
		AdCampaignCaption: "Ad campaign",
		EventCaption: "Event"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});