define("HomePageChartDesignerResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		DoughnutChartCaption: "Doughnut",
		WidgetColorLabel: "Chart color",
		WidgetThemeLabel: "Chart style",
		DisplayDataLabelCaption: "Show values",
		AddSeriesButtonCaption: "Add series",
		AggregationColumnLabel: "Column",
		AggregationTypeAvgCaption: "Average value",
		AggregationTypeCaption: "Function",
		AggregationTypeCountCaption: "Quantity",
		AggregationTypeLabel: "Function",
		AggregationTypeMaxCaption: "Max value",
		AggregationTypeMinCaption: "Min value",
		AggregationTypePlaceholder: "How to aggregate data?",
		AggregationTypeSumCaption: "Valuated amount",
		CancelButtonCaption: "Cancel",
		CaptionLabel: "Title",
		ChartAxisPositionLeft: "Left",
		ChartAxisPositionNone: "Do not display",
		ChartAxisPositionRight: "Right",
		ChartDesignerCaption: "Chart setup",
		ChartTypeCaption: "Chart type",
		CopySeriesButtonCaption: "Copy series",
		DateFormatCaption: "Format",
		DateFormatPlaceHolder: "Specify date format",
		DateTimeFormatDay: "Day",
		DateTimeFormatDayMonth: "Day \u0026 month",
		DateTimeFormatDayMonthYear: "Day, month, and year",
		DateTimeFormatHour: "Hour",
		DateTimeFormatMonth: "Month",
		DateTimeFormatMonthYear: "Month \u0026 year",
		DateTimeFormatWeek: "Week",
		DateTimeFormatYear: "Year",
		DefaultRelatedObjectCaptionFormat: "Connect \u0022{0}\u0022 object with current object by field",
		DeleteSeriesButtonCaption: "Delete series",
		DetailBindingColumnFormat: "",
		EntitySchemaNameCaption: "Object",
		EntitySchemaNameLabel: "Object",
		EntitySchemaNamePlaceholder: "From which object take the data?",
		FilterCaption: "Filter",
		FilterLabel: "Filter",
		FilterPropertiesCaption: "How to filter",
		FilterPropertiesLabel: "How to filter",
		FormatDecimalPrecision: "Number of digits after decimal point",
		FormatLabel: "Format",
		FormatPropertiesLabel: "How to display",
		InvalidSeriesConfig: "Required parameters are not filled in in the \u0022{0}\u0022 series",
		IsLegendEnabledCaption: "Show legend",
		IsPercentageModeCaption: "Values, %",
		IsStackedChartCaption: "With stacked",
		NameCaption: "Name",
		NewChartCaption: "New chart",
		NewWidget: "New widget",
		OrderByChartEntityColumn: "By resulting data",
		OrderByChartEntityColumnSeries: "By selection result of {0} series",
		OrderByGroupByField: "By grouping field",
		OrderDirectionASC: "Ascending",
		OrderDirectionCaption: "Sorting order",
		OrderDirectionDESC: "Descending",
		OrderPropertiesGroupLabel: "How to sort",
		QueryPropertiesLabel: "What to display",
		RelatedObjectCaptionFormat: "Connect \u0022{0}\u0022 object with \u0022{1}\u0022 {2} by field",
		RelatedObjectDetail: "detail",
		RelatedObjectSection: "section",
		SaveButtonCaption: "Save",
		SectionBindingColumnCaption: "Not associated with page data",
		SectionBindingColumnFormat: "Connect \u0022{0}\u0022 object with \u0022{1}\u0022 page by field",
		SectionBindingGroupCaption: "How to associate with page data",
		SeriesPropertiesCaption: "How to design?",
		SeriesTabCaption: "Series {0}",
		ShowPropertiesCaption: "How to display",
		SortCaption: "Sort by",
		StyleLabel: "Style",
		UnsupportedTypesMessage: "Incompatible chart types",
		UpdatedXAxisColumns: "You need to specify query grouping field for certain series",
		UseEmptyValueCaption: "Use empty value",
		UseSectionFiltrationCaption: "Use section filter",
		WidgetDesignerCaption: "Chart setup",
		XAxisCaption: "X-Axis label of series",
		XAxisColumnCaption: "Grouping field",
		XAxisColumnPlaceholder: "Select grouping field",
		XAxisDefaultCaption: "X-Axis label",
		XAxisDefaultCaptionTip: "If this field is empty label for the X-axis will be set from the value for the first series",
		XAxisPropertiesCaption: "How to group",
		YAxisCaption: "Y-Axis label of series",
		YAxisCaption2: "Index number caption",
		YAxisColumnCaption: "Column",
		YAxisColumnPlaceholder: "From which column take the data?",
		YAxisDefaultCaption: "Y-Axis label",
		YAxisDefaultCaptionTip: "If this field is empty label for the Y-axis will be set from the value for the first series",
		YAxisMaxValueLabel: "Max value",
		YAxisMinValueLabel: "Min value",
		YAxisPositionLabel: "Axis side",
		YAxisPropertiesCaption: "What to display"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {
		Settings: {
			source: 3,
			params: {
				schemaName: "HomePageChartDesigner",
				resourceItemName: "Settings",
				hash: "a5df3ed1d5e5511e3e23dc1875cc8769",
				resourceItemExtension: ".png"
			}
		}
	};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});