define("InvoiceResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		InvoiceCaption: "Invoice",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		NumberCaption: "Number",
		StartDateCaption: "Date",
		PrimaryAmountCaption: "Amount, base currency",
		PrimaryPaymentAmountCaption: "Payment amount, base currency",
		PaymentStatusCaption: "Payment status",
		OwnerCaption: "Owner",
		SupplierBillingInfoCaption: "Supplier banking details",
		RemindToOwnerCaption: "Remind owner",
		RemindToOwnerDateCaption: "Remind owner on",
		CustomerBillingInfoCaption: "Customer banking details",
		CurrencyCaption: "Currency",
		CurrencyRateCaption: "Exchange rate",
		AmountCaption: "Amount",
		DueDateCaption: "Paid on",
		PaymentAmountCaption: "Payment amount",
		NotesCaption: "Notes",
		AccountCaption: "Account",
		ContactCaption: "Contact",
		SupplierCaption: "Supplier",
		ProcessListenersCaption: "Active processes",
		ProjectCaption: "Project",
		OpportunityCaption: "Opportunity",
		ContractCaption: "Contract",
		OrderCaption: "Order",
		AmountWithoutTaxCaption: "Amount not including taxes",
		PrimaryAmountWithoutTaxCaption: "Amount not including taxes, base currency",
		PaymentAmountWithoutTaxCaption: "Payment amount not including taxes",
		PrimaryPaymentAmountWithoutTaxCaption: "Payment amount not including taxes, base currency"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});