define("Invoices_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		addRecord_qfv7c9y_caption: "Add new",
		AccountCategory_ariaLabel: "Dropdown",
		AccountIndustry_ariaLabel: "Dropdown",
		AccountInfoLabel_caption: "Account info",
		AccountWeb_caption: "Web link",
		AdditionalInfoTab_caption: "Additional information",
		addRecord_00g2j7n_caption: "Add new",
		addRecord_50cxtod_caption: "Add new",
		addRecord_828rar6_caption: "Add new",
		addRecord_rnfmy43_caption: "Add new",
		addRecord_rsjnj4q_caption: "Add new",
		Amount_tooltip: "Total amount of products in the invoice. This field is non-editable unless there are no records on the [Products] list",
		ApprovalListExpansionPanel_title: "Approvals list",
		ApprovalListRefreshButton_caption: "Refresh",
		ApprovalListSearch_placeholder: "Search",
		ApprovalsTab_caption: "Approvals",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		ContactEmail_caption: "Email address",
		ContactMobilePhone_caption: "Phone number",
		ContactPreferredLanguage_ariaLabel: "Dropdown",
		CustomerBankingDetails_tooltip: "Banking details of the customer. Go to the [Banking details] of the account page to add a new detail",
		CustomerProfileLabel_caption: "Customer profile",
		CustomerProfileTabContainer_caption: "Customer profile",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "General information",
		NewRecord: "New record",
		Number_tooltip: "Invoice number. This field is non-editable and is completed automatically according to the template",
		Owner_tooltip: "Full name of the record owner. Select the owner from the contacts registered as users in the system",
		ProductsAddButton_caption: "New",
		ProductsExpansionPanel_title: "Products",
		ProductsExportDataButton_caption: "Export to Excel",
		ProductsImportDataButton_caption: "Data import",
		ProductsListDS_DiscountPercent: "Discount",
		ProductsRefreshButton_caption: "Refresh",
		ProductsSettingsButton_caption: "Actions",
		Record: "Record",
		SaveButton: "Save",
		SendForApprovalButton_caption: "Send for approval",
		SetRecordRightsButtonCaption: "Set up access rights",
		SupplierBankingDetails_tooltip: "Banking details of the company that issued the invoice. These are based on the [Banking details] detail of the account page specified in the [Supplier] field",
		Timeline_caption: "Timeline",
		Timeline_label: "Timeline",
		TimelineTab_caption: "Timeline"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});