define("LandingiDesigner_PageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		LandingiGuideRow3Item1Text2_caption: "to Landingi.",
		LandingiGuideRow3Item1LogIn_caption: "Sign in",
		LandingiGuideRow3Item1Text1_caption: "or",
		LandingiGuideRow3Item1SignUp_caption: "Sign up",
		LandingiGuideRow3Item1Number_caption: "1",
		LandingiGuideRow2Item_caption: "Use the guide below to connect your web form to Creatio:",
		LandingiGuideRow1Item_caption: "Import landing page data to Creatio  ",
		LandingiButtonOpenLandingi_caption: "Open Landingi",
		LandingiRow3Item5LearnMore_caption: "Learn more.",
		LandingiRow3Item5Text_caption: "Select the object you want to generate in Creatio and map the form fields.",
		LandingiRow3Item5Number_caption: "5",
		LandingiRow3Item4LearnMore_caption: "Learn more.",
		LandingiRow3Item4Text_caption: "Paste the API key into the \u0022ApiKey\u0022 field of the window.",
		LandingiGuideRow3Item4Number_caption: "4",
		LandingiGuideRow3Item3Text_caption: "Click \u201CForm settings\u201D \u2192 click the \u201CIntegrations\u201D tab \u2192 select \u201CCreatio\u201D. This opens the field mapping window.",
		LandingiGuideRow3Item3Number_caption: "3",
		LandingiGuideRow3Item2Text_caption: "Create a new or open an existing landing page with a web form.",
		LandingiGuideRow3Item2Number_caption: "2",
		LandingiLogo_label: "Image to upload",
		LandingiImage_label: "Image to upload",
		PageTitle_caption: "Web forms and pages",
		LandingiButtonApiKey_caption: "Click to get your API key",
		LandingiInputApiKey_label: "API key",
		Label_hkvln2s_caption: "Label",
		LandingiInputApiKey_placeholder: "$ApiKey",
		LandingiButtonCopyApiKey_caption: "Copy",
		Label_efcfpm8_caption: "Label 2",
		OtherTabContainer_caption: "Other landing pages",
		Label_kjzmsex_caption: "Label 1",
		LandingiTabContainer_caption: "Landingi.com",
		OtherGuideRow3Item_caption: "Use the guide below to connect your web form to Creatio:",
		OtherGuideRow2Item_caption: "Import landing page data to Creatio",
		OtherGuideRow1Item_caption: "Other landing pages",
		OtherGuideRow4Item1Text_caption: "Create a new or use an existing landing page with a web form on your website.",
		OtherGuideRow4Item1Number_caption: "1",
		OtherGuideRow4Item2LearnMore_caption: "Learn more.",
		OtherGuideRow4Item2Text_caption: "Map the web form fields to the Creatio object fields.",
		OtherGuideRow4Item2Number_caption: "2",
		OtherGuideRow4Item3LearnMore_caption: "Learn more.",
		OtherGuideRow4Item3Text_caption: "Get the Webhook URL and use it to send submitted form data to Creatio.",
		OtherGuideRow4Item3Number_caption: "3",
		OtherButtonWebhookURL_caption: "Click to get your Webhook URL",
		OtherButtonCopyWebhookURL_caption: "Copy",
		OtherInputWebhookURL_label: "Webhook URL",
		Link_i79tylq_caption: "Learn more.",
		Label_mt1rmx2_caption: "Map the web form fields to the Creatio object fields.",
		Label_pauxvqf_caption: "2",
		Label_ieemavu_caption: "Create a new or use an existing landing page with a web form on your website.",
		Label_qg4y9ah_caption: "1",
		Label_jmjbq6c_caption: "to Landingi.",
		Link_9xqvs0c_caption: "Sign in",
		Label_2qvfd6b_caption: "or",
		Link_ho2z7gp_caption: "Sign up",
		FlexContainer_gouka7eText2_caption: "to Landingi.",
		FlexContainer_gouka7eText1_caption: "or",
		FlexContainer_gouka7eSignUp_caption: "Sign up",
		FlexContainer_gouka7eNumber_caption: "1",
		FlexContainer_gouka7eLogIn_caption: "Sign in",
		Label_474kag5_caption: "1",
		Link_jo57zvr_caption: "Learn more.",
		Label_q8zjjlq_caption: "Paste the API key into the \u0022ApiKey\u0022 field of the window.",
		Label_tdx8r1s_caption: "4",
		Label_wcio27m_caption: "Click \u201CForm settings\u201D \u2192 click the \u201CIntegrations\u201D tab \u2192 select \u201CCreatio\u201D. This opens the field mapping window.",
		FlexContainer_s0yfa8dText_caption: "Click \u201CForm settings\u201D \u2192 click the \u201CIntegrations\u201D tab \u2192 select \u201CCreatio\u201D. This opens the field mapping window.",
		FlexContainer_s0yfa8dNumber_caption: "3",
		Label_jtt523b_caption: "3",
		Label_n2sb98b_caption: "Create a new or open an existing landing page with a web form.",
		FlexContainer_7va8c3mText_caption: "Create a new or open an existing landing page with a web form.",
		FlexContainer_7va8c3mNumber_caption: "2",
		Label_f5vm7jv_caption: "2",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "General information",
		NewRecord: "New record",
		Record: "Record",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});