define("LDAPServerSettingsResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		LDAPServer: "Server name",
		SaveButtonCaption: "Save",
		CancelButtonCaption: "Cancel",
		CaptionLDAPServerSettings: "New LDAP server",
		QueryPropertiesLabel: "Server connection - General settings",
		LDAPUserCompanyAttribute: "Company name",
		LDAPAuthType: "Authentication type",
		LDAPServerLogin: "Administrator login",
		LDAPServerPassword: "Password",
		LDAPEntryModifiedOnAttribute: "Modification date attribute",
		LDAPSynchInterval: "Synchronization interval (hours)",
		UserAttributesLabel: "User attributes",
		LDAPUserFullNameAttribute: "User name",
		LDAPUserLoginAttribute: "Username",
		LDAPUserIdentityAttribute: "User Id",
		AttributesGroupOfUsersLabel: "User group attributes",
		FilteringConditionLabel: "Search data",
		LDAPGroupsEntry: "Groups domain name",
		LDAPUsersEntry: "Domain name",
		LDAPGroupNameAttribute: "LDAP group name",
		LDAPGroupIdentityAttribute: "Group Id",
		LDAPPageCaption: "LDAP server setup",
		LDAPUserEmailAttribute: "Email",
		LDAPUserPhoneAttribute: "Phone number",
		LDAPUserJobTitleAttribute: "Job title",
		LDAPUsersInGroupFilter: "List of group users",
		LDAPGroupsFilter: "List of groups",
		LDAPUsersFilter: "List of users",
		StartImportMessage: "LDAP organizational structure import process is running in the background. You will receive a notification when import is complete",
		KeyDistributionCenterCaption: "Key Distribution Center",
		LDAPSynchronizeOnlyGroups: "Synchronize only groups",
		LDAPSynchronizeOnlyGroupsTip: "When this option is enabled, users bound to the LDAP element manually will be deactivated",
		LDAPAllowLicenseDistribution: "Grant licenses",
		LDAPUseSecureConnectionTip: "To use LDAPS communication, please specify server name as \u0022server:port\u0022 (default port is 636).",
		LDAPUseSecureConnection: "Use SSL",
		LDAPGroupsFilterTip: "LDAP group synchronization filter. Use parentheses to separate logical expressions",
		LDAPUsersInGroupFilterTip: "Usergroup inclusion criteria",
		LDAPUsersFilterTip: "LDAP user synchronization filter. Use parentheses to separate logical expressions",
		LDAPServerLoginTip: "For Linux installation use domain\\login format",
		AuthenticationSettingsLabel: "Authentication settings",
		EditionsComparePageButtonCaption: "Compare all plans",
		LicOperationAccessDeniedMessage: "This feature is not available for Growth plan. Upgrade your subscription to Enterprise"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});