define("LeadOppHomePageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		OppsCreatedChartWidget_series_0: "Opportunity",
		OppsCreatedChartWidget_title: "Opportunities created (monthly)",
		LeadConversionChartWidget_series_3: "Closed won Opps",
		LeadConversionChartWidget_series_2: "Created Opps",
		LeadConversionChartWidget_series_1: "Open leads",
		LeadConversionChartWidget_series_0: "Total leads created",
		LeadConversionChartWidget_title: "Lead conversion",
		OpenOppsAmountCountIndicatorWidget_template: "{0}",
		OpenOppsAmountCountIndicatorWidget_title: "$ Open opportunities - CQ",
		OpenOppsIndicatorWidget_template: "{0}",
		OpenOppsIndicatorWidget_title: "# Open opportunities - CQ",
		OpenLeadsIndicatorWidget_template: "{0}",
		OpenLeadsIndicatorWidget_title: "# Open leads",
		OppAmountByCustomerNeedChartWidget_series_0: "Opportunity",
		OppAmountByCustomerNeedChartWidget_title: "Opportunity amount by customer need",
		NewVSExistingCustomersChartWidget_series_1: "Existing customers",
		NewVSExistingCustomersChartWidget_series_0: "New customers",
		NewVSExistingCustomersChartWidget_title: "New customers vs. Existing customers - CQ",
		OppsCreatedVSOppsClosedWidget_series_2: "Closed won",
		OppsCreatedVSOppsClosedWidget_series_1: "Closed lost",
		OppsCreatedVSOppsClosedWidget_series_0: "Created",
		OppsCreatedVSOppsClosedWidget_title: "$ Opportunities created vs. Opportunities closed",
		TotalOpportunityAmountWidget_template: "{0}",
		TotalOpportunityAmountWidget_title: "Total opportunity amount",
		AnnualAttainmentWidget_template: "{0}",
		AnnualAttainmentWidget_title: "Annual attainment",
		TotalOpportunityCountWidget_template: "{0}",
		TotalOpportunityCountWidget_title: "Total opportunity count",
		QuarterlyAttainmentWidget_template: "{0}",
		QuarterlyAttainmentWidget_title: "Quarterly attainment",
		SalesPipelineFunnelWidgete_title: "Sales pipeline",
		OldLeadsIndicatorWidget_template: "{0}",
		OldLeadsIndicatorWidget_title: "# Old leads (more than 7 days)",
		OppsCreatedVSOppsClosedChartWidget_series_2: "Closed won",
		OppsCreatedVSOppsClosedChartWidget_series_1: "Closed lost",
		OppsCreatedVSOppsClosedChartWidget_series_0: "Created",
		OppsCreatedVSOppsClosedChartWidget_title: "$ Opportunities created vs. Opportunities closed",
		LeadsCreatedChartWidget_series_0: "Lead",
		LeadsCreatedChartWidget_title: "Leads created (monthly)",
		OpenOppsCountIndicatorWidget_template: "{0}",
		OpenOppsCountIndicatorWidget_title: "# Open opportunities - CQ",
		TotalOpportunityAmountIndicatorWidget_template: "{0}",
		TotalOpportunityAmountIndicatorWidget_title: "Total opportunity amount",
		TotalOpportunityCountIndicatorWidget_template: "{0}",
		TotalOpportunityCountIndicatorWidget_title: "Total opportunity count",
		AnnualAttainmentIndicatorWidget_template: "{0}",
		AnnualAttainmentIndicatorWidget_title: "Annual attainment",
		QuarterlyAttainmentIndicatorWidget_template: "{0}",
		QuarterlyAttainmentIndicatorWidget_title: "Quarterly attainment"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});