define("LeadQualificationResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		LeadQualificationCaption: "Qualified lead",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		ProcessListenersCaption: "Active processes",
		NameCaption: "Lead",
		ContactBusinessPhoneCaption: "Business phone",
		ContactMobilePhoneCaption: "Mobile phone",
		ContactEmailCaption: "Email",
		AccountBusinessPhoneCaption: "Primary phone",
		AccountFaxCaption: "Fax",
		AccountWebsiteCaption: "Web",
		ContactCaption: "Contact",
		AccountCaption: "Account",
		GenderCaption: "Gender",
		FullJobTitleCaption: "Full job title",
		LeadContactNameCaption: "Contact name",
		JobCaption: "Job title",
		DepartmentCaption: "Department",
		SalutationCaption: "Salutation",
		DearCaption: "Salutation",
		AnnualRevenueCaption: "Annual revenue",
		EmployeesNumberCaption: "No. of employees",
		AccountCategoryCaption: "Category",
		IndustryCaption: "Industry",
		OwnershipCaption: "Business entity",
		LeadAccountNameCaption: "Account name",
		DecisionRoleCaption: "Role",
		LeadTypeCaption: "Customer need",
		LeadTypeRipenessCaption: "Need maturity",
		LeadContactAddressTypeCaption: "Address type",
		LeadContactCountryCaption: "Country",
		LeadContactRegionCaption: "State/province",
		LeadContactCityCaption: "City",
		LeadContactZipCaption: "ZIP/postal code",
		LeadContactAddressCaption: "Address",
		LeadSourceCaption: "Source",
		LeadAccountAddressTypeCaption: "Address type",
		LeadAccountCountryCaption: "Country",
		LeadAccountRegionCaption: "State/province",
		LeadAccountCityCaption: "City",
		LeadAccountZipCaption: "ZIP/postal code",
		LeadAccountAddressCaption: "Address"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});