define("Leads_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		OpportunityPlanningExpansionPanel_title: "Opportunity planning",
		addRecord_quqpon1_caption: "Add new",
		Budget_label: "Potential value",
		DecisionDate_label: "Expected close date",
		addRecord_o3h2431_caption: "Add new",
		ProductsSettingsButton_caption: "Actions",
		ProductsSearchFilter_placeholder: "Search",
		ProductsImportDataButton_caption: "Data import",
		ProductsExportDataButton_caption: "Export to Excel",
		ProductsRefreshButton_caption: "Refresh",
		ProductsAddButton_caption: "New",
		ProductsExpansionPanel_title: "Products",
		Timeline_label: "Timeline",
		Timeline_caption: "Timeline",
		CreateEmailButton_caption: "Create an email",
		CreateTaskButton_caption: "Create a task",
		NextStepsTabContainerHeaderLabel_caption: "Next steps",
		NextStepsTabContainer_caption: "Next steps",
		StageHistorySettingsButton_caption: "Actions",
		StageHistoryExpansionPanel_title: "Stage history",
		StageHistorySearchFilter_placeholder: "Search",
		StageHistoryExportDataButton_caption: "Export to Excel",
		StageHistoryRefreshButton_caption: "Refresh",
		LeadsByCustomerSearchFilter_placeholder: "Search",
		LeadsByCustomerImportDataButton_caption: "Data import",
		LeadsByCustomerExportDataButton_caption: "Export to Excel",
		LeadsByCustomerSettingsButton_caption: "Actions",
		LeadsByCustomerRefreshButton_caption: "Refresh",
		LeadsByCustomerAddButton_caption: "New",
		LeadsByCustomerExpansionPanel_title: "Leads by customer",
		OpportunitiesByCustomerSearchFilter_placeholder: "Search",
		OpportunitiesByCustomerImportDataButton_caption: "Data import",
		OpportunitiesByCustomerExportDataButton_caption: "Export to Excel",
		OpportunitiesByCustomerSettingsButton_caption: "Actions",
		OpportunitiesByCustomerRefreshButton_caption: "Refresh",
		OpportunitiesByCustomerAddButton_caption: "New",
		OpportunitiesByCustomerExpansionPanel_title: "Opportunities by customer",
		LeadDisqualifyReason_label: "Loss reason",
		ProductSuggestions_placeholder: "Note the products that can be offered to the customer",
		BusinessCase_placeholder: "Describe the customer\u0027s business need",
		ClosingDetails_placeholder: "Describe the reason why the lead was lost",
		Budget_tooltip: "Enter the potential revenue that this lead could bring",
		LeadsByCustomerListDS_QualifyStatus: "Stage",
		LeadsByCustomerListDS_LeadName: "Name",
		StageHistoryListDS_QualifyStatus: "Stage",
		PredictiveScore_tooltip: "The score indicates the probability of converting the Lead into an associated Opportunity. The value is calculated with the ML model",
		PredictiveScore_label: "Predictive probability",
		DecisionDate_tooltip: "Enter the expected closing date of the sale",
		OpportunitiesByCustomerListDS_DueDate: "Expected close date",
		OpportunitiesByCustomerListDS_Amount: "Total contract value",
		AccountLabel_caption: "Account info",
		addRecord_0j4btzv_caption: "Add new",
		AnnualRevenue_ariaLabel: "Dropdown",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		Commentary_label: "Comments",
		ContactLabel_caption: "Contact person",
		DefaultHeaderCaption: "Page title",
		EmployeesNumber_ariaLabel: "Dropdown",
		ExpansionPanel_8za599m_title: "",
		ExpansionPanel_g03me2b_title: "",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "Overview",
		GridDetailAddBtn_ldcvgh4_caption: "",
		GridDetailAddBtn_sci9mh1_caption: "",
		GridDetailExportDataBtn_u06l4gj_caption: "",
		GridDetailExportDataBtn_v8zj01r_caption: "",
		GridDetailImportDataBtn_rgkr5ar_caption: "",
		GridDetailImportDataBtn_s3jyha4_caption: "",
		GridDetailRefreshBtn_05v5x8h_caption: "",
		GridDetailRefreshBtn_y4vpzld_caption: "",
		GridDetailSearchFilter_blqjo8j_placeholder: "",
		GridDetailSearchFilter_cw3rvxp_placeholder: "",
		GridDetailSettingsBtn_he9mrdc_caption: "",
		GridDetailSettingsBtn_lv7ynoh_caption: "",
		HistoryTab_caption: "History",
		Industry_ariaLabel: "Dropdown",
		LeadName_label: "Name",
		NewRecord: "New record",
		ProcessingTab_caption: "Processing",
		Record: "Record",
		SalesTab_caption: "Sales",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights",
		SimilarLeadExpansionPanel_title: "Similar leads",
		SimilarLeadExportDataButton_caption: "Export to Excel",
		SimilarLeadListDS_LeadName: "Name",
		SimilarLeadListDS_QualifyStatus: "Stage",
		SimilarLeadRefreshButton_caption: "Refresh",
		SimilarLeadSearchFilter_placeholder: "Search",
		SimilarLeadSettingsButton_caption: "Actions",
		Type_ariaLabel: "Dropdown",
		Web_caption: "",
		ContactRegisterMethod_ariaLabel: "Dropdown",
		ContactChannel_ariaLabel: "Dropdown",
		ContactSource_ariaLabel: "Dropdown",
		addRecord_udcglv2_caption: "Add new",
		addRecord_hd0i1qq_caption: "Add new",
		addRecord_icp70f0_caption: "Add new"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});