define("MailboxSynchronizationSettingsPageModuleResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		OkCaptionEx: "Save",
		CancelCaptionEx: "Cancel",
		MailServerCaptionEx: "Mailbox type",
		UserNameCaptionEx: "Username",
		UserPasswordCaptionEx: "Password",
		PrivateMailboxCaptionEx: "Personal email account",
		AccessCaptionEx: "Access rights",
		UseEmailDownloadCaptionEx: "Download emails from mailbox",
		EmailDownloadGroupCaptionEx: "Receive emails",
		EmailDispatchGroupCaptionEx: "Send emails",
		EmailAutoDownloadCaptionEx: "Automatically download new emails every",
		MinutesCaptionEx: "minutes",
		EmailDownloadAllCaptionEx: "Download all emails from mailbox",
		StartWithDateCaptionEx: "Synchronize mail :",
		EmailDownloadFromGroupCaptionEx: "Download emails from customized folders",
		ChooseGroupCaptionEx: "Select folders",
		UseForEmailDispatchCaptionEx: "Send emails from mailbox",
		UseAsDefaultCaptionEx: "Use by default",
		PublicMailboxCaptionEx: "Shared email account",
		SMTPSettingsNotSetMessageEx: "Email parameters are not configured for the specified email provider",
		TitleCaptionEx: "Mailbox synchronization settings",
		MailboxNameCaptionEx: "Mailbox name",
		AddContactEmailMessageEx: "Add the specified email address to the list of your communication options?",
		ImapExceptionMessageEx: "Error occurred when trying to create the Creatio folder",
		NotSetSendingOrReceivingCheckMessageEx: "Please, select either the \u0022Enable email receiving\u0022 or \u0022Use mailbox to send messages\u0022 setting.",
		EmailsCyclicallyAddingIntervalTooSmallCaptionEx: "Time span for downloading emails should be greater than one minute",
		CantConnectWithoutCredentialsEx: "To select folders, you must first fill out all required fields",
		settingsExistsEx: "Unable to save the mailbox: name or address already exists. Change the name or email address and try again.",
		SenderEmailAddressCaptionEx: "User\u0027s email",
		ContactsGroupCaption: "Contacts",
		ImportContactsCaption: "Import contacts",
		AllCaption: "All",
		ImportContactsFromCategoriesCaption: "Import contacts from categories",
		ChooseFolderCaption: "Select folders",
		ChooseCategoryCaption: "Select categories",
		LinkContactToAccountCaption: "Connect contacts to accounts",
		ExportContactsCaption: "Export contacts",
		ExportContactsSelectedCaption: "Selected contacts",
		ExportContactsEmployersCaption: "Employees",
		ExportContactsCustomersCaption: "Customers",
		ExportContactsOwnerCaption: "My contacts",
		ExportFromGroupsCaption: "From folders",
		EmailAddressNotValid: "Invalid email address",
		ActivitiesGroupCaption: "Activities",
		ImportAppointmentsCaption: "Import meetings",
		FromCalendarsCaption: "From calendars",
		ChooseCalendarsCaption: "Select calendars",
		ImportTasksCaption: "Import tasks",
		FromFoldersCaption: "From folders",
		ExportActivitiesCaption: "Export activities",
		ExportActivitiesSelectedCaption: "Selected activities",
		ExportAppointmentsCaption: "Meetings",
		ExportTasksCaption: "Tasks",
		ExportActivitiesFromSchedulerCaption: "From calendar",
		ImportAppointmentsFromCaption: "Import activities starting from",
		IsAnonymousAuthenticationCaption: "Anonymous authentication ",
		SyncSettingNotSet: "Please, select a synchronization setting",
		ImportContactsFromFoldersNotSet: "Folders for importing contacts are not specified",
		ExportContactsFromGroupsNotSet: "Folders for exporting contacts are not specified",
		ExportContactsSelectedNotSet: "Selecting one of the contact export options is required",
		ImportAppointmentsFromCalendarsNotSet: "Calendars for importing meetings are not specified",
		ImportTasksFromFoldersNotSet: "Folders for importing tasks are not specified",
		ExportActivitiesFromGroupsNotSet: "Folders for exporting tasks and meetings are not specified",
		ExportActivitiesSelectedNotSet: "Selecting one of the export options is required",
		ExchangeAutoSynchronizationLabel: "Synchronize contacts and activities every ",
		IntervalTooSmallMessage: "Interval cannot be less than one minute",
		SharedMailBoxLabelCaption: "Use as a shared mailbox",
		OkCaption: "Save",
		CancelCaption: "Cancel",
		MailServerCaption: "Email provider",
		UserNameCaption: "Username",
		UserPasswordCaption: "Password",
		PrivateMailboxCaption: "Personal email account",
		AccessCaption: "Access rights",
		UseEmailDownloadCaption: "Download emails from mailbox",
		EmailDownloadGroupCaption: "Receive emails",
		EmailDispatchGroupCaption: "Send emails",
		EmailAutoDownloadCaption: "Automatically download new emails every",
		MinutesCaption: "minutes",
		EmailDownloadAllCaption: "Download all emails from mailbox",
		StartWithDateCaption: "Starting from",
		EmailDownloadFromGroupCaption: "Download emails from customized folders",
		ChooseGroupCaption: "Select folders",
		UseForEmailDispatchCaption: "Send emails from mailbox",
		UseAsDefaultCaption: "Use by default",
		PublicMailboxCaption: "Shared email account",
		SMTPSettingsNotSetMessage: "Email parameters are not configured for the specified email provider",
		TitleCaption: "Mailbox synchronization settings",
		MailboxNameCaption: "Mailbox name",
		AddContactEmailMessage: "Add the specified email address to the list of your communication options?",
		ImapExceptionMessage: "Error occurred when trying to create the Creatio folder",
		NotSetSendingOrReceivingCheckMessage: "Please, select either the \u0022Enable email receiving\u0022 or \u0022Use mailbox to send messages\u0022 setting.",
		EmailsCyclicallyAddingIntervalTooSmallCaption: "Time span for downloading emails should be greater than one minute",
		CantConnectWithoutCredentials: "To select folders, you must first fill in the following: email provider, username, password",
		settingsExists: "Unable to save the mailbox: name or address already exists. Change the name or email address and try again.",
		SenderEmailAddressCaption: "User\u0027s email"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});