define("MLModelResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		MLModelCaption: "ML model",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		ProcessListenersCaption: "Active processes",
		NameCaption: "Name",
		DescriptionCaption: "Description",
		TrainFrequencyCaption: "Retrain after, days",
		TrainedOnCaption: "When the model was trained",
		TriedToTrainOnCaption: "Last attempt to train date",
		MetaDataCaption: "Query metadata for selecting additional training data",
		MetaDataLczCaption: "Localizable part of metadata",
		TrainingSetQueryCaption: "Query for selecting additional training data",
		RootSchemaUIdCaption: "Object",
		StateCaption: "Status",
		InstanceMetricCaption: "Evaluation metric",
		MetricThresholdCaption: "Quality metric lower limit",
		PredictionEnabledCaption: "Prediction enabled",
		TrainSessionIdCaption: "Current training session",
		MLProblemTypeCaption: "Type",
		ModelInstanceUIdCaption: "Model instance Id",
		LastErrorCaption: "Last error message text",
		NotesCaption: "Notes",
		BatchPredictedOnCaption: "Batch prediction date",
		BatchPredictionQueryCaption: "Query for selecting additional prediction data",
		TargetColumnUIdCaption: "Outcome column",
		BatchPredictionStartMethodCaption: "Method of batch prediction start",
		TrainingMinimumRecordsCountCaption: "Minimum training record count",
		TrainingMaxRecordsCountCaption: "Maximum training record count",
		TrainingFilterDataCaption: "Training query filter",
		PredictedResultColumnUIdCaption: "Prediction result column",
		TrainingOutputFilterDataCaption: "Positive result condition in training dataset",
		BatchPredictionFilterDataCaption: "Batch prediction query filter",
		MLConfidentValueMethodCaption: "Predicted value selection method",
		ConfidentValueLowEdgeCaption: "Lower limit of probability for predicted value selection",
		CFUserColumnPathCaption: "Recommended to (Subject)",
		CFItemColumnPathCaption: "Recommended object",
		CFInteractionValueColumnPathCaption: "Recommendation dependency column",
		ListPredictResultSchemaUIdCaption: "List predict result schema",
		ListPredictResultSubjectColumnCaption: "List prediction subject column",
		ListPredictResultObjectColumnCaption: "List prediction result object column",
		ListPredictResultValueColumnCaption: "List prediction result value column",
		ListPredictResultModelColumnCaption: "List prediction result model column",
		ListPredictResultDateColumnCaption: "List prediction result date column",
		FactorsCountsCaption: "List of factors count",
		RegularizationValuesCaption: "List of regularization values",
		PredictionSchemaUIdCaption: "Prediction schema",
		LowerScoreThresholdCaption: "Lower score threshold",
		LastTrainingErrorCaption: "Last training error",
		SequenceItemValueColumnPathCaption: "Sequence item value column",
		SequenceItemPositionColumnPathCaption: "Sequence item position column",
		SequenceIdentifierColumnPathCaption: "Sequence identifier column"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});