define("Opportunities_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		AccountLabel_caption: "Account info",
		ContactLabel_caption: "Contact person",
		AnnualRevenue_ariaLabel: "",
		EmployeesNumber_ariaLabel: "",
		Industry_ariaLabel: "",
		Type_ariaLabel: "",
		Web_caption: "",
		HistoryTab_caption: "History",
		ProductsTab_caption: "Products",
		OpportunityInsightsTab_caption: "Opportunity insights",
		ProcessingTab_caption: "Processing",
		OverviewTab_caption: "Overview",
		addRecord_b045nw6_caption: "Add new",
		addRecord_4fhxgqr_caption: "Add new",
		addRecord_r39nt24_caption: "Add new",
		ProductsSearchFilter_placeholder: "Search",
		ProductsImportDataButton_caption: "Data import",
		ProductsExportDataButton_caption: "Export to Excel",
		ProductsSettingsButton_caption: "Actions",
		ProductsRefreshButton_caption: "Refresh",
		ProductsAddButton_caption: "New",
		ProductsExpansionPanel_title: "Products",
		OurPerspectiveExpansionPanel_title: "Our perspective",
		CustomerPerspectiveExpansionPanel_title: "Customer perspective",
		RecommendedProductSearchFilter_placeholder: "Search",
		RecommendedProductExportDataButton_caption: "Export to Excel",
		RecommendedProductSettingsButton_caption: "Actions",
		RecommendedProductRefreshButton_caption: "Refresh",
		RecommendedProductExpansionPanel_title: "Recommended products",
		DueDate_label: "Expected close date",
		Amount_label: "Total contract value",
		addRecord_0hxbi4r_caption: "Add new",
		ContactRolesSettingsButton_caption: "Actions",
		ContactRolesImportDataButton_caption: "Data import",
		ContactRolesExportDataButton_caption: "Export to Excel",
		ContactRolesAddButton_caption: "New",
		ContactRolesSearchFilter_placeholder: "Search",
		ContactRolesRefreshButton_caption: "Refresh",
		ContactRolesExpansionPanel_title: "Contact roles",
		CompetitorsListDS_IsWinner: "Won by",
		CompetitorsListDS_Competitor: "Competitor",
		CompetitorsSearchFilter_placeholder: "Search",
		CompetitorsImportDataButton_caption: "Data import",
		CompetitorsExportDataButton_caption: "Export to Excel",
		CompetitorsSettingsButton_caption: "Actions",
		CompetitorsRefreshButton_caption: "Refresh",
		CompetitorsAddButton_caption: "New",
		CompetitorsExpansionPanel_title: "Competitors",
		OpportunityTeamSearchFilter_placeholder: "Search",
		OpportunityTeamImportDataButton_caption: "Data import",
		OpportunityTeamExportDataButton_caption: "Export to Excel",
		OpportunityTeamSettingsButton_caption: "Actions",
		OpportunityTeamRefreshButton_caption: "Refresh",
		OpportunityTeamAddButton_caption: "New",
		OpportunityTeamExpansionPanel_title: "Opportunity team",
		IsPrimary_label: "New customer",
		Timeline_label: "Timeline",
		Timeline_caption: "Timeline",
		NextStepsTabContainer_caption: "Next steps",
		CreateEmailButton_caption: "Create an email",
		CreateTaskButton_caption: "Create a task",
		NextStepsTabContainerHeaderLabel_caption: "Next steps",
		StageHistorySearchFilter_placeholder: "Search",
		StageHistoryExportDataButton_caption: "Export to Excel",
		StageHistorySettingsButton_caption: "Actions",
		StageHistoryExpansionPanel_title: "Stage history",
		StageHistoryRefreshButton_caption: "Refresh",
		LeadsSearchFilter_placeholder: "Search",
		LeadsImportDataButton_caption: "Data import",
		LeadsExportDataButton_caption: "Export to Excel",
		LeadsSettingsButton_caption: "Actions",
		LeadsRefreshButton_caption: "Refresh",
		LeadsAddButton_caption: "New",
		LeadsExpansionPanel_title: "Leads",
		OpportunitiesByCustomerSearchFilter_placeholder: "Search",
		OpportunitiesByCustomerImportDataButton_caption: "Data import",
		OpportunitiesByCustomerExportDataButton_caption: "Export to Excel",
		OpportunitiesByCustomerSettingsButton_caption: "Actions",
		OpportunitiesByCustomerRefreshButton_caption: "Refresh",
		OpportunitiesByCustomerAddButton_caption: "New",
		OpportunitiesByCustomerExpansionPanel_title: "Opportunities by customer",
		NextKeyActionExpansionPanel_title: "Next key action",
		OpportunityType_label: "Sales channel",
		OutgoingCallsMetric_template: "{0}",
		OutgoingCallsMetric_title: "Outgoing calls",
		EmailsSentMetric_template: "{0}",
		EmailsSentMetric_title: "Emails sent",
		DaysAtCurrentStageMetric_template: "{0}",
		DaysAtCurrentStageMetric_title: "Days at current stage",
		DaysInFunnelMetric_template: "{0}",
		DaysInFunnelMetric_title: "Days in funnel",
		CloseReason_label: "Loss reason",
		ProductSuggestions_placeholder: "Note the products that can be offered to the customer",
		Weaknesses_placeholder: "What are our weaknesses?",
		Strength_placeholder: "What are our advantage?",
		EngagementTactic_placeholder: "Tactics for engaging the cooperation",
		WhyOurCompany_placeholder: "Why do customers choose us?",
		BuyingProcess_placeholder: "What is the buying process?",
		WhyNow_placeholder: "Why the customer needs it now?",
		Why_placeholder: "Why the customer wants it?",
		What_placeholder: "What the customer wants?",
		ClosingDetails_placeholder: "Describe the reason why the sale was lost",
		PrintButton_caption: "Attach quotation",
		ProductsListDS_ProductPrice: "Base price",
		LeadsListDS_QualifyStatus: "Stage",
		LeadsListDS_LeadName: "Name",
		RunOppMgmtProcButton_caption: "Run opportunity management process",
		PredictiveProbability_tooltip: "The score indicates the probability of winning the Opportunity. The value is calculated with the ML model",
		QuickFilterShowAllLeads_config_caption: "Show all leads by customer",
		DueDate_tooltip: "Enter the expected closing date of the sale. This field is completed automatically and becomes non-editable when the opportunity moves to the final stage",
		Amount_tooltip: "Enter the potential revenue to be associated with the contract as a result of the winning sale. This field is completed automatically when products are added to the opportunity",
		OpportunitiesByCustomerListDS_Amount: "Total contract value",
		OpportunitiesByCustomerListDS_DueDate: "Expected close date",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "Overview",
		NewRecord: "New record",
		Record: "Record",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});