define("OpportunityResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		OpportunityCaption: "Opportunity",
		IdCaption: "Id",
		TitleCaption: "Name",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		ProcessListenersCaption: "Active processes",
		TypeCaption: "Type",
		StageCaption: "Stage",
		DueDateCaption: "Closed on",
		CloseReasonCaption: "Reason for closing",
		OwnerCaption: "Owner",
		NotesCaption: "Notes",
		AccountCaption: "Account",
		CategoryCaption: "Category",
		MoodCaption: "Mood",
		IsPrimaryCaption: "New customer",
		PartnerCaption: "Partner",
		BudgetCaption: "Budget",
		ProbabilityCaption: "Probability, %",
		AmountCaption: "Opportunity amount",
		SourceCaption: "Source",
		ResponsibleDepartmentCaption: "Division",
		WeaknessesCaption: "Our weaknesses",
		StrengthCaption: "Our strengths",
		TacticCaption: "Sales tactics",
		CheckDateCaption: "Verified on",
		ProcessIdCaption: "Process Id",
		WinnerCaption: "Winner",
		ContactCaption: "Contact",
		CompletenessCaption: "Completeness",
		DescriptionCaption: "Description",
		LeadTypeCaption: "Customer need",
		PredictiveProbabilityCaption: "Predictive probability",
		MoodValueCaption: "Manager\u0027s mood value",
		GroupCaption: "Assignees group",
		ProductSuggestionsCaption: "Product suggestions",
		BuyingProcessCaption: "Buying process",
		WhyNowCaption: "Why now?",
		WhyCaption: "Why?",
		WhatCaption: "What?",
		EngagementTacticCaption: "Engagement tactic",
		WhyOurCompanyCaption: "Why our company?",
		ForecastCommitCaption: "Commit to forecast",
		DecisionMakerCaption: "Decision maker",
		ClosingDetailsCaption: "Closing details",
		ByProcessCaption: "By process"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});