define("Orders_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		addRecord_fqbv4qt_caption: "Add new",
		AccountAddress_label: "Account address",
		AccountCategory_ariaLabel: "Dropdown",
		AccountIndustry_ariaLabel: "Dropdown",
		AccountLabel_caption: "Account info",
		AccountWeb_caption: "Web link",
		addRecord_dbyq7n8_caption: "Add new",
		addRecord_gge12ha_caption: "Add new",
		addRecord_mb4zwk4_caption: "Add new",
		addRecord_xx9pdmu_caption: "Add new",
		ApprovalListExpansionPanel_title: "Approvals list",
		ApprovalListRefreshButton_caption: "Refresh",
		ApprovalListSearch_placeholder: "Search",
		ApprovalsTab_caption: "Approvals",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		ContactAddress_label: "Contact address",
		ContactEmail_caption: "Email address",
		ContactMobilePhone_caption: "Phone number",
		ContactPreferredLanguage_ariaLabel: "Dropdown",
		CustomerProfileTabContainer_caption: "Customer profile",
		CustomerProfileTabContainerHeaderLabel_caption: "Customer profile",
		DefaultHeaderCaption: "Page title",
		DocumentsExpansionPanel_title: "Documents",
		DocumentsExportDataButton_caption: "Export to Excel",
		DocumentsRefreshButton_caption: "Refresh",
		DocumentsSearch_placeholder: "Search",
		DocumentsTab_caption: "Documents",
		ExpansionPanel_dbtaxlc_title: "Expanded list",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "Products",
		GridDetail_tviz7gfDS_DiscountPercent: "Discount",
		GridDetailAddBtn_n0rv6tu_caption: "New",
		GridDetailExportDataBtn_thhv3as_caption: "Export to Excel",
		GridDetailImportDataBtn_pu57mnb_caption: "Data import",
		GridDetailRefreshBtn_0of7x3y_caption: "Refresh",
		GridDetailSearchFilter_v38rkqs_placeholder: "Search",
		GridDetailSettingsBtn_i02a9fi_caption: "Actions",
		InstallmentPlanExpansionPanel_title: "Installment plan",
		InstallmentPlanRefreshButton_caption: "Refresh",
		InstallmentPlanSearchFilter_placeholder: "Search",
		InvoicesAddButton_caption: "New",
		InvoicesExpansionPanel_title: "Invoices",
		InvoicesExportDataButton_caption: "Export to Excel",
		InvoicesImportDataButton_caption: "Data import",
		InvoicesRefreshButton_caption: "Refresh",
		InvoicesSearchFilter_placeholder: "Search",
		InvoicesSettingsButton_caption: "Actions",
		NewRecord: "New record",
		OrderInfoLabel_caption: "Order info",
		PaymentDeliveryTab_caption: "Payment \u0026 Delivery",
		ProductsAddButton_caption: "New",
		ProductsExpansionPanel_title: "Products",
		ProductsExportDataButton_caption: "Export to Excel",
		ProductsImportDataButton_caption: "Data import",
		ProductsRefreshButton_caption: "Refresh",
		ProductsSearchFilter_placeholder: "Search",
		ProductsSettingsButton_caption: "Actions",
		Record: "Record",
		SaveButton: "Save",
		SendForApprovalButton_caption: "Send for approval",
		SetRecordRightsButtonCaption: "Set up access rights",
		Timeline_caption: "Timeline",
		Timeline_label: "Timeline",
		TimelineTab_caption: "Timeline",
		TotalWidgetTitle_caption: "Total, $",
		TotalWidgetValue_caption: "3,492.00",
		InstallmentPlanImportDataButton_caption: "Data import",
		InstallmentPlanExportDataButton_caption: "Export to Excel",
		InstallmentPlanSettingsButton_caption: "Actions"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});