define("OrderContractHomePageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		ContractsCreatedChartWidget_series_0: "Contract",
		ContractsCreatedChartWidget_title: "Contracts created (monthly)",
		InvoicesCreatedChartWidget_series_0: "Invoice",
		InvoicesCreatedChartWidget_title: "Invoices created (monthly)",
		OrdersCreatedChartWidget_series_0: "Order",
		OrdersCreatedChartWidget_title: "Orders created (monthly)",
		ChartWidget_wi4z1ws_series_0: "Contract",
		ChartWidget_wi4z1ws_title: "Contracts by status",
		ChartWidget_qgvayvj_series_0: "Contract",
		ChartWidget_qgvayvj_title: "Contracts created (monthly)",
		ChartWidget_anaj6zg_series_0: "Invoice",
		ChartWidget_anaj6zg_title: "invoices by status",
		ChartWidget_merhd6a_series_0: "Invoice",
		ChartWidget_merhd6a_title: "Invoices created (monthly)",
		OrdersByStatusChartWidget_series_0: "Order",
		OrdersByStatusChartWidget_title: "Orders by status",
		ChartWidget_eyfwrk2_series_0: "Order",
		ChartWidget_eyfwrk2_title: "Orders created (monthly)",
		ChartWidget_djbhe0q_series_0: "Order",
		ChartWidget_djbhe0q_title: "Orders by status",
		AmountOpenOrdersIndicatorWidget_template: "{0}",
		AmountOpenOrdersIndicatorWidget_title: "$ Open orders - CM",
		IndicatorWidget_x6r2o4n_template: "{0}",
		IndicatorWidget_x6r2o4n_title: "Average order margin",
		IndicatorWidget_1cqufv2_template: "{0}",
		IndicatorWidget_1cqufv2_title: "# Open orders - CM",
		IndicatorWidget_2k21igd_template: "{0}",
		IndicatorWidget_2k21igd_title: "$ Open orders - CM",
		IndicatorWidget_f7l1d5n_template: "{0}",
		IndicatorWidget_f7l1d5n_title: "# Unpaid invoices - CM",
		OrdersByChannelsChartWidget_series_0: "Order",
		OrdersByChannelsChartWidget_title: "Orders by channel",
		OrderByChannelsChartWidget_series_0: "Order",
		OrderByChannelsChartWidget_title: "Orders by channels",
		IndicatorWidget_osjb0uh_template: "{0}",
		IndicatorWidget_osjb0uh_title: "Total order amount",
		ChartWidget_2ci9ftl_series_0: "Order",
		ChartWidget_2ci9ftl_title: "Order dynamics by number",
		ChartWidget_060bryj_series_0: "Order",
		ChartWidget_060bryj_title: "Order dynamics by amount",
		OrdersCreatedVSOrdersClosedChartWidget_series_2: "Completed",
		OrdersCreatedVSOrdersClosedChartWidget_series_1: "In progress",
		OrdersCreatedVSOrdersClosedChartWidget_series_0: "Created",
		OrdersCreatedVSOrdersClosedChartWidget_title: "$ Orders created vs. Orders closed",
		TotalOrderAmountIndicatorWidget_template: "{0}",
		TotalOrderAmountIndicatorWidget_title: "Total order amount",
		AnnualAttainmentIndicatorWidget_template: "{0}",
		AnnualAttainmentIndicatorWidget_title: "Annual attainment",
		TotalOrderCountIndicatorWidget_template: "{0}",
		TotalOrderCountIndicatorWidget_title: "Total order count",
		QuarterlyAttainmentIndicatorWidget_template: "{0}",
		QuarterlyAttainmentIndicatorWidget_title: "Quarterly attainment",
		ContractsByStatusChartWidget_series_0: "Contract",
		ContractsByStatusChartWidget_title: "Contracts by status",
		InvoicesByStatusChartWidget_series_0: "Invoice",
		InvoicesByStatusChartWidget_title: "Invoices by status",
		UnpaidSnvoicesIndicatorWidget_template: "{0}",
		UnpaidSnvoicesIndicatorWidget_title: "# Unpaid invoices - CM",
		OrdersMarginIndicatorWidgeto4n_template: "{0}",
		OrdersMarginIndicatorWidgeto4n_title: "Average order margin",
		NumberOpenOrdersIndicatorWidget_template: "{0}",
		NumberOpenOrdersIndicatorWidget_title: "# Open orders - CM",
		OrdersByChannelChartWidget_series_0: "Order",
		OrdersByChannelChartWidget_title: "Orders by channel",
		OrderDynamicsByNumberChartWidget_series_0: "Order",
		OrderDynamicsByNumberChartWidget_title: "Order dynamics by number",
		OrderDynamicsByAmountChartWidget_series_0: "Order",
		OrderDynamicsByAmountChartWidget_title: "Order dynamics by amount"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});