define("Products_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		ProductPriceListRefreshButton_caption: "Refresh",
		GridDetailSearchFilter_1wl0gtb_placeholder: "Search",
		GridDetailImportDataBtn_vo9mcul_caption: "Data import",
		GridDetailExportDataBtn_3w8sz9o_caption: "Export to Excel",
		GridDetailSettingsBtn_f1b73j7_caption: "Actions",
		GridDetailRefreshBtn_ny5fg9g_caption: "Refresh",
		GridDetailAddBtn_2u8w5ou_caption: "New",
		ExpansionPanel_bzx1bdx_title: "Product price",
		GridDetailSearchFilter_b4abwkk_placeholder: "Search",
		GridDetailImportDataBtn_05pe1tu_caption: "Data import",
		GridDetailExportDataBtn_p8xdb3v_caption: "Export to Excel",
		GridDetailSettingsBtn_5u633cm_caption: "Actions",
		GridDetailRefreshBtn_ujkbirs_caption: "Refresh",
		GridDetailAddBtn_wq35d3r_caption: "New",
		ExpansionPanel_d8u3ioo_title: "Expanded list",
		TabContainer_c14w0u0_caption: "Prices and availability",
		PricesExpansionPanel_title: "Prices",
		GridDetailSearchFilter_nf22n1q_placeholder: "Search",
		GridDetailImportDataBtn_tyxy8vz_caption: "Data import",
		GridDetailExportDataBtn_15dodzf_caption: "Export to Excel",
		GridDetailSettingsBtn_uzfuq5a_caption: "Actions",
		GridDetailRefreshBtn_8eyutp9_caption: "Refresh",
		GridDetailAddBtn_51lho3i_caption: "New",
		ExpansionPanel_byjqiod_title: "Availability",
		ProductInStockRefreshButton_caption: "Refresh",
		GridDetailSearchFilter_o3zyuv6_placeholder: "Search",
		GridDetailImportDataBtn_guqd7x1_caption: "Data import",
		GridDetailExportDataBtn_eiymfk8_caption: "Export to Excel",
		GridDetailSettingsBtn_5ntnqjk_caption: "Actions",
		GridDetailRefreshBtn_qqf4p8c_caption: "Refresh",
		GridDetailAddBtn_vqh1486_caption: "New",
		ExpansionPanel_8916g2e_title: "Units",
		GridDetail_snzncmyDS_UnitShortName: "Short name",
		ProductPriceListImportDataButton_caption: "Data import",
		ProductPriceListExportDataButton_caption: "Export to Excel",
		ProductPriceListSearchFilter_placeholder: "Search",
		ProductPriceListSettingsButton_caption: "Actions",
		ProductInStockListImportDataButton_caption: "Data import",
		ProductInStockListExportDataButton_caption: "Export to Excel",
		ProductInStockListSettingsButton_caption: "Actions",
		ProductInStockListSearchFilter_placeholder: "Search",
		UnitsExpansionPanel_title: "Units",
		ProductUnitListRefreshButton_caption: "Refresh",
		ProductUnitListImportDataButton_caption: "Data import",
		ProductUnitListExportDataButton_caption: "Export to Excel",
		ProductUnitListSettingsButton_caption: "Actions",
		ProductUnitListSearchFilter_placeholder: "Search",
		AvailabilityExpansionPanel_title: "Availability",
		PricesTab_caption: "Prices and availability",
		addRecord_iqfhsij_caption: "Add new",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		Benefits_placeholder: "Enter benefits",
		Brand_placeholder: "Select brand",
		CancelButton: "Cancel",
		Category_placeholder: "Select category",
		CloseButton: "Close",
		Currency_placeholder: "Select currency",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralConditions_placeholder: "Enter general conditions",
		GeneralInfoTab_caption: "General information",
		Link_placeholder: "Enter web link",
		Name_placeholder: "Enter product name",
		NewRecord: "New record",
		Notes_placeholder: "Enter notes",
		Owner_placeholder: "Select owner",
		Price_placeholder: "Enter price",
		Record: "Record",
		RichTextEditor_caption: "Rich text",
		RichTextEditor_label: "Rich text",
		RichTextEditor_placeholder: "Enter notes",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights",
		ShortDescription_placeholder: "Enter short description",
		Tax_placeholder: "Select tax",
		Type_placeholder: "Select type"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});