define("ProjectResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		ProjectCaption: "Project",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		NotesCaption: "Notes",
		ProcessListenersCaption: "Active processes",
		NameCaption: "Name",
		AccountCaption: "Account",
		ContactCaption: "Contact",
		ProjectEntryTypeCaption: "Project record type",
		TypeCaption: "Type",
		OwnerCaption: "Owner",
		StatusCaption: "Status",
		StartDateCaption: "Start",
		EndDateCaption: "End",
		DurationCaption: "Duration",
		DeadlineCaption: "Deadline",
		SupplierCaption: "Supplier",
		OpportunityCaption: "Opportunity",
		ParentProjectCaption: "Parent item",
		ActualCompletionCaption: "Completion %",
		IsAutoCalcCompletionCaption: "Calculate automatically",
		PlanIncomeCaption: "Expected revenue",
		FactIncomeCaption: "Actual revenue",
		IncomeDevCaption: "Revenue deviation",
		IncomeDevPercCaption: "Revenue deviation, %",
		PlanExternalCostCaption: "Expected total cost",
		FactExternalCostCaption: "Actual total cost",
		ExternalCostDevCaption: "Total cost deviation",
		PlanExternalDevPercCaption: "Total cost deviation, %",
		PlanExpenseCaption: "Expected direct expense",
		FactExpenseCaption: "Actual direct expense",
		ExpenseDevCaption: "Direct expenses deviation",
		ExpenseDevPercCaption: "Direct expenses deviation, %",
		PlanInternalCostCaption: "Expected prime cost",
		FactInternalCostCaption: "Actual prime cost",
		InternalCostDevCaption: "Prime cost deviation",
		PlanInternalDevPercCaption: "Prime cost deviation, %",
		PlanMarginCaption: "Expected margin",
		PlanMarginPercCaption: "Expected margin, %",
		FactMarginCaption: "Actual margin",
		FactMarginPercCaption: "Actual margin, %",
		MarginDevCaption: "Margin deviation",
		MarginDevPercCaption: "Margin deviation, %",
		PositionCaption: "Position"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});