define("Services_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		Label_x01rs14_caption: "General info",
		TabContainer_cmfqamf_caption: "History",
		ResolutionTimeUnit_label: "Resolution time",
		addRecord_jd4aj44_caption: "Add new",
		addRecord_u8lsmco_caption: "Add new",
		ResponseTimeUnit_label: "Response time",
		addRecord_g3cn7mq_caption: "Add new",
		Label_4qxqmbk_caption: "Terms",
		ComboboxSearchTextAction_q2nrnan_caption: "Add new",
		addRecord_i5xmdt7_caption: "Add new",
		addRecord_03s9cot_caption: "Add new",
		addRecord_f54okj6_caption: "Add new",
		addRecord_512tqpw_caption: "Add new",
		GridDetailSearchFilter_9qs4sib_placeholder: "Search",
		GridDetailImportDataBtn_1cppkoy_caption: "Data import",
		GridDetailExportDataBtn_qywk5qg_caption: "Export to Excel",
		GridDetailSettingsBtn_7vinrmk_caption: "Actions",
		GridDetailRefreshBtn_zrtkjak_caption: "Refresh",
		GridDetailAddBtn_l985z0l_caption: "New",
		ExpansionPanel_hk5gmbt_title: "Cases",
		ServicePactRefreshButton_caption: "Refresh",
		CasesRefreshButton_caption: "Refresh",
		GridDetailSearchFilter_sbh1em5_placeholder: "Search",
		GridDetailImportDataBtn_nx1fnqs_caption: "Data import",
		GridDetailExportDataBtn_ecccny6_caption: "Export to Excel",
		GridDetailSettingsBtn_4ddsz60_caption: "Actions",
		GridDetailRefreshBtn_iixd0yt_caption: "Refresh",
		GridDetailAddBtn_6ybvphu_caption: "New",
		ExpansionPanel_p94hdm6_title: "Service agreements",
		ServiceTeamMemberRefreshButton_caption: "Refresh",
		GridDetailRefreshButton_caption: "Refresh",
		GridDetailSearchFilter_nfnjt32_placeholder: "Search",
		GridDetailImportDataBtn_d8q6i3r_caption: "Data import",
		GridDetailExportDataBtn_huey3az_caption: "Export to Excel",
		GridDetailSettingsBtn_051u662_caption: "Actions",
		GridDetailRefreshBtn_5vs7aur_caption: "Refresh",
		GridDetailAddBtn_cf3yrbf_caption: "New",
		ExpansionPanel_bzlj5in_title: "Responsible service team",
		RelatedServicesRefreshButton_caption: "Refresh",
		GridDetailSearchFilter_uowgd08_placeholder: "Search",
		GridDetailImportDataBtn_19cqo5j_caption: "Data import",
		GridDetailExportDataBtn_199cc1u_caption: "Export to Excel",
		GridDetailSettingsBtn_fvm5lxp_caption: "Actions",
		GridDetailRefreshBtn_brx41dw_caption: "Refresh",
		GridDetailAddBtn_5rm00x4_caption: "New",
		ExpansionPanel_my13urh_title: "Related services",
		RelatedServicesList_6f31e5ef: "Service",
		ServiceTeamMemberExportDataButton_caption: "Export to Excel",
		ServiceTeamMemberSearchFilter_placeholder: "Search",
		ServiceTeamMemberSettingsButton_caption: "Actions",
		ServiceTeamMemberExpansionPanel_title: "Responsible service team",
		TermsLabel_caption: "Terms",
		GeneralInfoLabel_caption: "General info",
		ServiceTeamMemberImportDataButton_caption: "Data import",
		ServicePactSearchFilter_placeholder: "Search",
		ServicePactsImportDataButton_caption: "Data import",
		ServicePactsExportDataButton_caption: "Export to Excel",
		ServicePactSettingsButton_caption: "Actions",
		ServicePactExpansionPanel_title: "Related service agreements",
		CasesSearchFilter_placeholder: "Search",
		CasesImportDataButton_caption: "Data import",
		CasesExportDataButton_caption: "Export to Excel",
		CasesSettingsButton_caption: "Actions",
		CasesExpansionPanel_title: "Cases",
		HistoryTab_caption: "Case history",
		RelatedServicesImportDataButton_caption: "Data import",
		RelatedServicesExportDataButton_caption: "Export to Excel",
		RelatedServicesSearchFilter_placeholder: "Search",
		RelatedServicesSettingsButton_caption: "Actions",
		RelatedServicesExpansionPanel_title: "Related services",
		ResolutionTimeValue_label: "Value",
		ResponseTimeValue_label: "Value",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "Service profile",
		NewRecord: "New record",
		Record: "Record",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});