define("ServiceAgreements_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		GridDetailSearchFilter_xky7p65_placeholder: "Search",
		GridDetailImportDataBtn_2iui5ze_caption: "Data import",
		GridDetailExportDataBtn_86v8c8q_caption: "Export to Excel",
		GridDetailSettingsBtn_4f0xlzk_caption: "Actions",
		GridDetailRefreshBtn_d9dg1pp_caption: "Refresh",
		GridDetailAddBtn_k1hrc5b_caption: "New",
		ExpansionPanel_c9gf0bh_title: "Service recipients",
		addRecord_3ok2cmj_caption: "Add new",
		addRecord_zb4my2r_caption: "Add new",
		addRecord_o0novp4_caption: "Add new",
		addRecord_a3wxnrt_caption: "Add new",
		addRecord_1f56dia_caption: "Add new",
		ServiceRecipientsRefreshButton_caption: "Refresh",
		ServiceRecipientsSearchFilter_placeholder: "Search",
		GridDetailSearchFilter_gh8z01y_placeholder: "Search",
		GridDetailImportDataBtn_qukq886_caption: "Data import",
		GridDetailExportDataBtn_f8frxif_caption: "Export to Excel",
		GridDetailSettingsBtn_ac6uu1y_caption: "Actions",
		GridDetailRefreshBtn_hg1j1um_caption: "Refresh",
		GridDetailAddBtn_3qfcd1h_caption: "New",
		ExpansionPanel_241ukdf_title: "Service recipients",
		GridDetailSearchFilter_a4wkgx3_placeholder: "Search",
		GridDetailImportDataBtn_wmmf3ni_caption: "Data import",
		GridDetailExportDataBtn_9uzotmf_caption: "Export to Excel",
		GridDetailSettingsBtn_snaham7_caption: "Actions",
		GridDetailRefreshBtn_4ok1vso_caption: "Refresh",
		GridDetailAddBtn_ow8bu8c_caption: "New",
		ExpansionPanel_9hxk0eq_title: "Services",
		TabContainer_6ipl1ss_caption: "Case history",
		GridDetailSearchFilter_v9udmk0_placeholder: "Search",
		GridDetailImportDataBtn_9v0xcbp_caption: "Data import",
		GridDetailExportDataBtn_1lecmt6_caption: "Export to Excel",
		GridDetailSettingsBtn_vun9t8m_caption: "Actions",
		GridDetailRefreshBtn_obmjo3f_caption: "Refresh",
		GridDetailAddBtn_3iqrzc1_caption: "New",
		ExpansionPanel_v5dftap_title: "Cases",
		CasesSearchFilter_placeholder: "Search",
		CasesImportDataButton_caption: "Data import",
		CasesExportDataButton_caption: "Export to Excel",
		CasesSettingsButton_caption: "Actions",
		CasesRefreshButton_caption: "Refresh",
		CasesExpansionPanel_title: "Cases",
		ServicesSearchFilter_placeholder: "Search",
		ServicesImportDataButton_caption: "Data import",
		ServicesExportDataButton_caption: "Export to Excel",
		ServicesSettingsButton_caption: "Actions",
		ServicesAddButton_caption: "New",
		ServicesRefreshButton_caption: "Refresh",
		ServicesExpansionPanel_title: "Available services in contract",
		ServiceRecipientsExpansionPanel_title: "Active service recipients",
		ServiceRecipientsImportDataButton_caption: "Data import",
		ServiceRecipientsExportDataButton_caption: "Export to Excel",
		ServiceRecipientsSettingsButton_caption: "Actions",
		Label_eay1yqv_caption: "General info",
		MenuItem_tizwwo4_caption: "Menu item",
		GeneralInfoLabel_caption: "General info",
		ServicesList_310bc671: "Service",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "Contract terms",
		NewRecord: "New record",
		Record: "Record",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});