define("SimilarLeadResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		SimilarLeadCaption: "Similar lead",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		NotesCaption: "Notes",
		AccountCaption: "Account name",
		ContactCaption: "Contact name",
		TitleCaption: "Salutation",
		FullJobTitleCaption: "Full job title",
		StatusCaption: "Status",
		InformationSourceCaption: "Information source",
		IndustryCaption: "Industry",
		AnnualRevenueCaption: "Annual revenue",
		EmployeesNumberCaption: "No. of employees",
		BusinesPhoneCaption: "Business phone",
		MobilePhoneCaption: "Mobile phone",
		EmailCaption: "Email",
		FaxCaption: "Fax",
		WebsiteCaption: "Web",
		AddressTypeCaption: "Address type",
		CountryCaption: "Country",
		RegionCaption: "State/province",
		CityCaption: "City",
		ZipCaption: "ZIP/postal code",
		AddressCaption: "Address",
		DoNotUseEmailCaption: "Do not use email",
		DoNotUsePhoneCaption: "Do not use phone",
		DoNotUseFaxCaption: "Do not use fax",
		DoNotUseSMSCaption: "Do not use SMS",
		DoNotUseMailCaption: "Do not use mail",
		CommentaryCaption: "Notes",
		QualifiedContactCaption: "Contact",
		QualifiedAccountCaption: "Account",
		LeadNameCaption: "Lead",
		ProcessListenersCaption: "Active processes",
		CountryStrCaption: "Country (string)",
		RegionStrCaption: "State/province (string)",
		CityStrCaption: "City (string)",
		WebFormCaption: "Landing page",
		LeadTypeCaption: "Customer need",
		LeadTypeStatusCaption: "Need maturity",
		LeadDisqualifyReasonCaption: "Disqualification reason",
		AccountCategoryCaption: "Category",
		AccountOwnershipCaption: "Business entity",
		DepartmentCaption: "Department",
		GenderCaption: "Gender",
		JobCaption: "Job title",
		DecisionRoleCaption: "Role",
		QualifyStatusCaption: "Lead stage",
		DearCaption: "Recipient\u0027s name",
		QualificationProcessIdCaption: "QualificationProcessId",
		OwnerCaption: "Owner",
		RemindToOwnerCaption: "Remind owner",
		SalesOwnerCaption: "Opportunity owner",
		BudgetCaption: "Budget",
		MeetingDateCaption: "Meeting date and time",
		DecisionDateCaption: "Decision date",
		ShowDistributionPageCaption: "Display distribution page",
		BpmHrefCaption: "BpmHref",
		BpmRefCaption: "Redirection website",
		RegisterMethodCaption: "Registration method",
		LeadSourceCaption: "Source",
		LeadMediumCaption: "Channel",
		OpportunityDepartmentCaption: "Sales division",
		IdentificationPassedCaption: "Identification passed",
		CampaignCaption: "Campaign",
		BulkEmailCaption: "Bulk email",
		QualifiedCaption: "Qualified",
		SaleParticipantCaption: "Opportunity participant",
		QualifiedPercentCaption: "% of qualified",
		SalePercentCaption: "% of opportunities",
		StartLeadManagementProcessCaption: "Run process while lead generation",
		SaleTypeCaption: "Type of sale",
		ScoreCaption: "Score",
		QualificationPassedCaption: "Qualification passed",
		EventCaption: "Event",
		NextActualizationDateCaption: "Next actualization date",
		BpmSessionIdCaption: "BpmSessionId",
		PredictiveScoreCaption: "Predictive score",
		MovedToFinalStateOnCaption: "Date of transfer to the final state",
		OpportunityCaption: "Opportunity",
		PartnerCaption: "Partner",
		PartnerOwnerCaption: "Partner\u0027s deal owner",
		PartnerTypeCaption: "Partner type",
		GroupCaption: "Assignees group",
		LeadTypeDetailsCaption: "Lead type",
		UtmCampaignStrCaption: "utm_campaign",
		UtmSourceStrCaption: "utm_source",
		UtmMediumStrCaption: "utm_medium",
		UtmContentStrCaption: "utm_content",
		UtmTermStrCaption: "utm_term",
		SalesChannelCaption: "Sales channel",
		ProductSuggestionsCaption: "Product suggestions",
		BusinessCaseCaption: "Business case",
		ClosingDetailsCaption: "Closing details",
		LeadGenExtendedLeadInfoCaption: "Extended lead information",
		SocialMetadataCaption: "Social metadata",
		OrderCaption: "Order"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});