define("SsoSettingsV2Resources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		RefreshButtonCaption: "",
		SearchFilter_placeholder: "",
		Button_rv37f3w_caption: "",
		Button_wbldjlj_caption: "",
		Button_c1n5qgv_caption: "",
		Button_7jo0us3_caption: "",
		TabContainer_i2vhfxs_caption: "",
		TabContainer_y2orwdm_caption: "",
		AddButton_caption: "New",
		TabContainer_lmbm2dd_caption: "",
		TabContainer_JIT_caption: "JIT provisioning",
		Label_AdditionalInformation_caption: "Additional information",
		TabContainer_SsoProviders_caption: "SSO Identity provider",
		TabContainer_xyznn6k_caption: "",
		Button_g2hjeg5_caption: "",
		Button_g2hjeg5: "",
		Button_JIT_caption: "Just-In-Time provisioning",
		Button_Azure_caption: "Single Sign On via Azure AD",
		MenuItem_AddNewProvider_caption: "",
		Button_OneLogin_caption: "Single Sign On via OneLogin",
		Button_ADFS_caption: "Single Sign On via AD FS",
		TabContainer_JIT_OPENID_caption: "OPENID provisioning",
		Checkbox_UseJIT_tooltip: "Use Just-in-Time Provisioning for general users",
		Checkbox_UseJIT_label: "Create and update users data when log in (Just-In-Time Provisioning)",
		Button_y1ig7vh_caption: "Single Sign On via Cognito",
		ExpansionPanel_OpenIdAttributes_title: "OpenID provisioning",
		ExpansionPanel_SamlProvisioning_title: "SAML data to contact fields mapping",
		SaveButton_caption: "Save",
		ExpansionPanel_SsoProviders_title: "External identity providers",
		ExpansionPanel_OpenIdProvisioning_title: "OpenID data to contact fields mapping",
		SsoSettingsTempate_ColumnCaption: "Protocol",
		EntityID_ColumnCaption: "Entity ID",
		BackButton_caption: "Back",
		Button_18ejr71_caption: "",
		ActionButton_caption: "Actions",
		Button_Data_Import: "Import",
		DefaultHeaderCaption: "Page title",
		EmptySectionPlaceholderSubHead: "Add a new record to make it look prettier",
		EmptySectionPlaceholderTitle: "The section has no records",
		FilteredEmptySectionPlaceholderSubHead: "Clear the filter or change its conditions",
		FilteredEmptySectionPlaceholderTitle: "There are no records matching the filter criteria",
		ListTitleCaption: "List title",
		MenuItem_ExportToExel_caption: "Export to Excel",
		MenuItem_ImportFromExel_caption: "Excel",
		OpenLandingDesignerCaption: "Web forms and pages"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});