define("Tasks_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		addRecord_1g27yyy_caption: "Add new",
		addRecord_d7tgh1o_caption: "Add new",
		addRecord_1f3uxqe_caption: "Add new",
		addRecord_2203v7p_caption: "Add new",
		addRecord_dgwsv5d_caption: "Add new",
		addRecord_gd4s8lw_caption: "Add new",
		addRecord_ov8b6oh_caption: "Add new",
		addRecord_s3niqqb_caption: "Add new",
		addRecord_xozmcce_caption: "Add new",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainer_caption: "Attachments",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		Button_rupn8sfCaption: "Upload",
		Button_uey36i4Caption: "Refresh",
		CancelButton: "Cancel",
		CloseButton: "Close",
		DefaultHeaderCaption: "Page title",
		ExpansionPanel_9kt2jf4_title: "Info",
		ExpansionPanel_gayd5lc_title: "Attachments",
		ExpansionPanel_hbptvvf_title: "Participants",
		FeedTabContainer_caption: "Feed",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "General information",
		GridDetailAddBtn_65zfh1c_caption: "New",
		GridDetailAddBtn_b84d905_caption: "Upload",
		GridDetailAddBtn_j463qn2_caption: "New",
		GridDetailExportDataBtn_jhs983p_caption: "Export to Excel",
		GridDetailExportDataBtn_zajcdyb_caption: "Export to Excel",
		GridDetailImportDataBtn_70xbu27_caption: "Data import",
		GridDetailImportDataBtn_xq02vnt_caption: "Data import",
		GridDetailRefreshBtn_gfethnt_caption: "Refresh",
		GridDetailRefreshBtn_m9f2zlj_caption: "Refresh",
		GridDetailRefreshBtn_nv2l3mt_caption: "Refresh",
		GridDetailSearchFilter_sc547hp_placeholder: "Search",
		GridDetailSearchFilter_ui9rjm1_placeholder: "Search",
		GridDetailSearchFilter_wxs6sib_placeholder: "Search",
		GridDetailSettingsBtn_076nxwc_caption: "Actions",
		GridDetailSettingsBtn_gt57y67_caption: "Actions",
		Label_2i2b8cv_caption: "Executors",
		Label_7p83djj_caption: "Reminders",
		Label_7ux4r92_caption: "Attachments",
		Label_bouo1vp_caption: "Feed",
		Label_s2umkbw_caption: "Details",
		Label_t0rm6mn_caption: "Connections",
		NewRecord: "New record",
		Notes_placeholder: "Type details for this task",
		Record: "Record",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights",
		TabContainer_4rzb4bw_caption: "Connections",
		TabContainer_es7ne17Caption: "Attachments",
		TabContainer_itw82y1_caption: "Attachments",
		TabContainer_ko8xzk9_caption: "Feed"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});