define("TouchResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		TouchCaption: "Web sessions",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		ProcessListenersCaption: "Active processes",
		CityCaption: "City",
		PageReferrerCaption: "Page referrer URL",
		DurationCaption: "Web session duration, seconds",
		DomainCaption: "Domain",
		LanguageCaption: "Language",
		IPCaption: "IP address",
		CountryCaption: "Country",
		ContactCaption: "Contact",
		UtmTermStrCaption: "utm_term",
		UtmSourceStrCaption: "utm_source",
		UtmMediumStrCaption: "utm_medium",
		UtmContentStrCaption: "utm_content",
		UtmCampaignStrCaption: "utm_campaign",
		PlatformCaption: "Platform",
		DeviceCaption: "Device",
		SessionIdCaption: "Session",
		MatomoVisitorIdCaption: "Matomo visitor identifier",
		MatomoUserIdCaption: "Matomo user identifier",
		LastActionDateTimeCaption: "Last action date",
		PlatformStrCaption: "Platform (string)",
		LanguageStrCaption: "Language (string)",
		DeviceStrCaption: "Device (string)",
		CountryStrCaption: "Country (string)",
		CityStrCaption: "City (string)",
		StartDateCaption: "Session start date",
		CountryCodeCaption: "Country code",
		RegionCodeCaption: "Region code",
		RegionStrCaption: "Region (string)",
		RegionCaption: "Region",
		LocationCaption: "Location",
		ReferrerTypeStrCaption: "Referrer type (string)",
		ReferrerNameStrCaption: "Referrer name (string)",
		ReferrerKeywordCaption: "Referrer keyword",
		ReferrerUrlCaption: "Referrer URL",
		ReferrerTypeCaption: "Referrer type",
		ReferrerNameCaption: "Referrer name",
		UtmIdStrCaption: "utm_id",
		SourceCaption: "Source",
		ChannelCaption: "Channel",
		NotesCaption: "Notes",
		AccountEmployeesNumberCaption: "No. of employees (range)",
		AccountExactNoOfEmployeesCaption: "Exact number of employees",
		FacebookProfileUrlCaption: "Facebook profile",
		WebsiteCaption: "Website",
		LinkedInProfileUrlCaption: "LinkedIn profile",
		SubIndustryCaption: "SubIndustry",
		IndustryCaption: "Industry",
		AccountCaption: "Account",
		AccountNameTextCaption: "Account name",
		MatomoSiteIdCaption: "Matomo website identifier"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});