define("UISwitcher_ListPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		RefreshButtonCaption: "Refresh",
		SearchFilter_placeholder: "Search",
		Label_w4l6bvu_caption: "Exceptions by object",
		TabContainer_FormPagePreferences_caption: "Form page preferences",
		Label_79wq37f_caption: "Label 2",
		TabContainer_tj1hrvk_caption: "Tab 2",
		Label_11ovdqk_caption: "Label 1",
		TabContainer_7zkwdx9_caption: "UI Preferences",
		ImageInput_hthz6lq_label: "Image to upload",
		Label_kypyo9r_caption: "Freedom UI is turned on for current user ",
		Label_3974cnb_caption: "notification panels.",
		Label_BasicCreatioInClassicUI_caption: "for basic Creatio operations, and \u200E",
		Label_SidePanel_caption: "side panel, quick access buttons \u200E",
		Label_ClassicUIComprises_caption: "Classic UI comprises \u200E",
		Button_SwitchToFreedomUI_caption: "Switch to Freedom UI for all users",
		Label_SwitchToFreedomUI_caption: "Switch to Freedom UI for all users or configure rules for users and user groups.",
		Label_ClassicUIIsTurnedOn_caption: "Classic UI is turned on for current user",
		Button_049tffm_caption: "Switch to Classic UI for all users",
		Label_4694jts_caption: "Switch to Classic UI for all users or configure rules for users and user groups.",
		Button_3cqudcz_caption: "Learn more in the Academy",
		Label_zjl1x3m_caption: "Classic UI is a previous generation Creatio shell.",
		Label_eq7j083_caption: "operations, and \u200E",
		Label_c5wqbcb_caption: "navigation panel, quick access buttons \u200E",
		Label_wfajkic_caption: "Freedom UI comprises \u200E",
		Button_SwitchToClassicUI_caption: "Switch to Classic UI for all users",
		Button_06h5mw9_caption: "Button",
		Label_SwitchToClassicUI_caption: "Switch to Classic UI for all users or configure rules for users and user groups.",
		Label_aqcc6h7_caption: "Label",
		Button_GoToAcademyFreedomUIPage_caption: "Learn more in the Academy",
		Button_xdqttan_caption: "Button",
		Label_GeneralInfoFreedomUI_caption: "Freedom UI is a Creatio shell that encompasses the latest and greatest UX best practices to streamline the app design process and user adoption, all while providing a high level of personalization. ",
		Label_qoekgd3_caption: "Label",
		Label_nbp3mgw_caption: "operations, and \u200E",
		Label_brd8k4m_caption: "notification panels.",
		Label_Operations_caption: "operations, and \u200E",
		Label_lj5xrn1_caption: "\u200Efor basic Creatio \u200E",
		Label_uo76z7z_caption: "\u200Efor basic Creatio \u200E",
		Label_NavigationPanel_caption: "navigation panel, quick access buttons \u200E",
		Label_a3o0cq1_caption: "Freedom UI comprises \u200E",
		Label_FreedomUIComprises_caption: "Freedom UI comprises \u200E",
		Label_3iu4fr2_caption: "Freedom UI comprises \u200E",
		Label_OperationsFreedomUI_caption: "operations, and \u200E",
		Label_BasicCreatioFreedomUI_caption: "\u200Efor basic Creatio \u200E",
		DataGrid_ja3432rDS_Position: "Priority",
		DataGrid_ja3432rDS_BooleanValue: "Freedom UI is enabled",
		DataGrid_ja3432rDS_SysAdminUnit: "User or group",
		Button_zhwpyft_caption: "Edit",
		Label_ConfigurationUIForUsersOrGroups_caption: "Configuration UI for users or groups ",
		Label_mwyxb8e_caption: "Label",
		RefreshButton_caption: "Refresh",
		Label_FreedomUIGeneralRule_caption: "Freedom UI sections always open Freedom pages regardless of settings and exceptions.",
		Label_6e4jqdb_caption: "Label",
		Label_8nygpk8_caption: "Attention",
		Button_GoToAcademyExamplesPage_caption: "Learn more in the Academy",
		Button_lomqbqz_caption: "Button",
		Label_DifferentSectionUI_caption: "3. Use different section UI depending on a group of users",
		Label_53235pv_caption: "2. Use Freedom pages in Classic UI sections",
		Label_FreedomPagesInClassicUI_caption: "2. Use Freedom pages in Classic UI sections",
		Label_gu3mif2_caption: "1. Turn on Freedom UI for a group of users",
		Label_TurnOnFreedomUIForGroup_caption: "1. Turn on Freedom UI for a group of users",
		Label_new6m7h_caption: "To ensure comfortable user adoption of new Creatio UI, you can use various combinations of shell and form page settings. This lets you enable updated pages as they are finished.",
		Label_GeneralInfoCombinations_caption: "To ensure comfortable user adoption of new Creatio UI, you can use various combinations of shell and form page settings. This lets you enable updated pages as they are finished.",
		Label_jxmi5sy_caption: "Label",
		Label_ExamplesOfSettingCombinations_caption: "Examples of setting combinations",
		Label_cfje792_caption: "Label",
		Label_rgodibg_caption: "By default, Classic UI uses",
		Button_hfd8cgw_caption: "Learn more in the Academy",
		Label_nhepfnk_caption: "Specifies which form page to open in the Classic UI shell if the object has both Freedom and Classic pages. Currently, Creatio uses Freedom pages when you add, view, or edit records. Freedom pages use the new generation UI.",
		Label_GeneralInfoClassicPagesInFreedomUI_caption: "Specifies which form page to open in the Freedom UI shell if the object has both Freedom and Classic pages. Currently, Creatio uses Classic pages when you add, view, or edit records. Classic pages use the previous generation UI.",
		Label_ClassicPagesInFreedomUIColor_caption: "Classic pages",
		Label_dyddzl5_caption: "Freedom pages",
		Button_r6hth0y_caption: "Learn more in the Academy",
		Label_e3f9hja_caption: "Specifies which form page to open in the Freedom UI shell if the object has both Freedom and Classic pages. Currently, Creatio uses Freedom pages when you add, view, or edit records. Freedom pages use the new generation UI.",
		Button_GoToAcademyFreedomPagesInFreedomUI_caption: "Learn more in the Academy",
		Button_2m209eq_caption: "Button",
		Label_GeneralInfoFreedomPagesInFreedomUI_caption: "Specifies which form page to open in the Freedom UI shell if the object has both Freedom and Classic pages. Currently, Creatio uses Freedom pages when you add, view, or edit records. Freedom pages use the new generation UI.",
		Label_l5hm0aq_caption: "Label",
		Button_l197vr3_caption: "Edit",
		Label_ln3sccr_caption: "Freedom pages",
		Label_6qhdbpe_caption: "By default, Freedom UI uses",
		Label_wt38c8e_caption: "Specifies which form page to open in the Classic UI shell if the object has both Freedom and Classic pages. Currently, Creatio uses Classic pages when you add, view, or edit records. Classic pages use the previous generation UI.",
		Label_ClassicPagesInClassicUIColor_caption: "Classic pages",
		Label_9f3idus_caption: "2. Use Freedom pages in Classic UI sections",
		Button_EditConfigurationUIForUsers_caption: "Edit",
		Label_LogoutRequired_caption: "To apply the changes users must log out of Creatio and log back",
		Label_vg2a5mi_caption: "Label",
		Button_TurnOnFreedomPagesinClassicUI_caption: "Edit",
		Button_TurnOnClassicPagesinClassicUI_caption: "Edit",
		Button_TurnOnFreedomPagesinFreedomUI_caption: "Edit",
		Button_TurnOnClassicPagesinFreedomUI_caption: "Edit",
		ActionButton_caption: "Actions",
		Button_Data_Import: "Import",
		DefaultHeaderCaption: "Page title",
		EmptySectionPlaceholderSubHead: "Add a new record to make it look prettier",
		EmptySectionPlaceholderTitle: "The section has no records",
		FilteredEmptySectionPlaceholderSubHead: "Clear the filter or change its conditions",
		FilteredEmptySectionPlaceholderTitle: "There are no records matching the filter criteria",
		ListTitleCaption: "List title",
		MenuItem_ExportToExel_caption: "Export to Excel",
		MenuItem_ImportFromExel_caption: "Excel",
		OpenLandingDesignerCaption: "Web forms and pages"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});