define("VwGroupSysAdminUnitResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		VwGroupSysAdminUnitCaption: "Folder - Administration object (view)",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		NameCaption: "Name",
		DescriptionCaption: "Description",
		SysAdminUnitTypeValueCaption: "Type",
		ParentRoleCaption: "Inherited from",
		ContactCaption: "Contact",
		AccountCaption: "Account",
		IsDirectoryEntryCaption: "Domain user",
		TimeZoneIdCaption: "Time zone",
		UserPasswordCaption: "Password",
		ActiveCaption: "Active",
		SynchronizeWithLDAPCaption: "Synchronize with LDAP",
		LDAPEntryCaption: "LDAP element",
		LDAPEntryIdCaption: "LDAP element Id",
		LDAPEntryDNCaption: "LDAP element unique name",
		LoggedInCaption: "Logged in",
		ProcessListenersCaption: "Active processes",
		SysCultureCaption: "Culture",
		LoginAttemptCountCaption: "Number of logon attempts",
		SourceControlLoginCaption: "Repository login",
		SourceControlPasswordCaption: "Repository password",
		PasswordExpireDateCaption: "Password expiration date",
		HomePageCaption: "Home page",
		ConnectionTypeCaption: "Connection type",
		UnblockTimeCaption: "Unlocking time",
		ForceChangePasswordCaption: "Reset password",
		DateTimeFormatCaption: "Display date and time format",
		SessionTimeoutCaption: "Session timeout (minutes)",
		PortalAccountCaption: "PortalAccount",
		LDAPElementCaption: "LDAP element",
		EmailCaption: "Email",
		OpenIDSubCaption: "OpenID sub claim",
		PhoneCaption: "Phone",
		WeekFirstDayCaption: "First day of week"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});