define("VwProcessLibResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		VwProcessLibCaption: "Process library (view)",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		UIdCaption: "UId",
		NameCaption: "Name",
		CaptionCaption: "Title",
		ManagerNameCaption: "Manager name",
		ParentCaption: "Parent",
		ExtendParentCaption: "Extends parent",
		IsChangedCaption: "Modified",
		IsLockedCaption: "Locked",
		MetaDataCaption: "Metadata",
		MetaDataModifiedOnCaption: "Metadata changed",
		SysPackageCaption: "Package",
		PackageUIdCaption: "Package Id",
		SysWorkspaceCaption: "Workspace",
		DescriptionCaption: "Description",
		ProcessListenersCaption: "Active processes",
		NeedUpdateSourceCodeCaption: "Source code update required",
		NeedUpdateStructureCaption: "Update required: Table in database",
		NeedInstallCaption: "Needs installing",
		IsMaxVersionCaption: "Maximum version",
		TagPropertyCaption: "Type",
		EnabledCaption: "Active",
		VersionCaption: "Version",
		ProcessSchemaTypeCaption: "Process schema type",
		SysSchemaIdCaption: "Unique identifier of workspace schema",
		AddToRunButtonCaption: "Display in run process button list",
		IsActiveVersionCaption: "Actual version",
		VersionParentIdCaption: "Parent version Id",
		HasStartEventCaption: "HasStartEvent",
		VersionParentUIdCaption: "VersionParentUId",
		StartOptionsImageCaption: "Start options image",
		IsProcessTracingCaption: "Trace enabled"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});