define("VwSysAdminUnitResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		VwSysAdminUnitCaption: "Users/roles (view)",
		IdCaption: "Id",
		CreatedOnCaption: "Created on",
		CreatedByCaption: "Created by",
		ModifiedOnCaption: "Modified on",
		ModifiedByCaption: "Modified by",
		NameCaption: "Name",
		DescriptionCaption: "Description",
		SysAdminUnitTypeCaption: "Type",
		ParentRoleCaption: "Inherited from",
		ContactCaption: "Contact",
		AccountCaption: "Account",
		IsDirectoryEntryCaption: "Domain user",
		TimeZoneCaption: "Time zone",
		UserPasswordCaption: "Password",
		ActiveCaption: "Active",
		LoggedInCaption: "Logged in now",
		LDAPEntryCaption: "LDAP element",
		SynchronizeWithLDAPCaption: "Synchronize with LDAP",
		LDAPEntryIdCaption: "LDAP element Id",
		LDAPEntryDNCaption: "LDAP element unique name ",
		ProcessListenersCaption: "Active processes",
		SysCultureCaption: "Culture",
		PasswordExpireDateCaption: "Password expiration date",
		HomePageCaption: "Home page",
		ConnectionTypeCaption: "Connection type",
		ForceChangePasswordCaption: "Reset password",
		LDAPElementCaption: "LDAP element",
		UserConnectionTypeCaption: "User Connection Type",
		DateTimeFormatCaption: "Date and time format",
		SysAdminUnitCaption: "System administration object",
		SessionTimeoutCaption: "Session timeout",
		EmailCaption: "Email",
		PhoneCaption: "Phone"
	};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages};
});