define("Webhooks_FormPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		GridDetailSearchFilter_mlkx9ya_placeholder: "Search",
		GridDetailImportDataBtn_7zlgukc_caption: "Data import",
		GridDetailExportDataBtn_79lllnb_caption: "Export to Excel",
		GridDetailSettingsBtn_uujeiz5_caption: "Actions",
		GridDetailRefreshBtn_5putbnx_caption: "Refresh",
		GridDetailAddBtn_7yddngl_caption: "New",
		ExpansionPanel_ke87l82_title: "Logs",
		addRecord_cft7qje_caption: "Add new",
		Button_d5cyapl_caption: "Refresh",
		SearchFilter_mtu5uuy_mlkx9ya_placeholder: "Search",
		Button_d5cyapl_5putbnx_caption: "Refresh",
		Button_sbfnxqz_caption: "Export to Excel",
		Button_sbfnxqz_uujeiz5_caption: "Actions",
		Label_yemsgau_caption: "Parse exceptions",
		GridDetailSettingsBtn_caption: "Export to Excel",
		Label_3skux8s_caption: "Webhook",
		SearchFilter_mtu5uuy_placeholder: "Search",
		EmptySectionPlaceholderSubHead: "Add a new record to make it look prettier",
		EmptySectionPlaceholderTitle: "The section has no records",
		FilteredEmptySectionPlaceholderSubHead: "Clear the filter or change its conditions",
		FilteredEmptySectionPlaceholderTitle: "There are no records matching the filter criteria",
		ExportLogGridActionButton_caption: "Export to Excel",
		Label_m2bn6gt_caption: "Webhook details",
		OpenLogsMenuItem_caption: "Open logs",
		ActionMenuButton_caption: "Actions",
		MenuItem_pc7dfn0_caption: "Open logs",
		MenuItem_w5sfudk_caption: "Export to Excel",
		Button_j3n0gm2_caption: "Export to Excel",
		ErrorsLogGridTitle_caption: "Parsing errors",
		SearchLogGridActionButton_placeholder: "Search",
		RefreshLogGridActionButton_caption: "Refresh",
		ExportMenuItem_caption: "Export to Excel",
		ActionsMenuButton_caption: "Actions",
		PageFixedTitle_caption: "Webhook",
		AttachmentAddButtonCaption: "Upload",
		AttachmentRefreshButtonCaption: "Refresh",
		AttachmentsTabContainerCaption: "Attachments",
		BackButton: "Back",
		CancelButton: "Cancel",
		CloseButton: "Close",
		DefaultHeaderCaption: "Page title",
		FeedTabContainerCaption: "Feed",
		GeneralInfoTab_caption: "Webhook details",
		NewRecord: "New record",
		Record: "Record",
		SaveButton: "Save",
		SetRecordRightsButtonCaption: "Set up access rights"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});