define("Webhooks_ListPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		RefreshButtonCaption: "Refresh",
		SearchFilter_placeholder: "Search",
		Timer_by6cua2_label: "Timer",
		Timer_by6cua2_caption: "Timer",
		PDS_RequestBody: "Request Body",
		PDS_WebhookSource: "Source",
		PDS_CreatedOn: "Date",
		ChartWidget_adnuhcw_yAxis: "Count of webhooks",
		ChartWidget_adnuhcw_xAxis: "Date",
		ChartWidget_adnuhcw_series_0: "Webhook",
		ChartWidget_adnuhcw_title: "Dynamics of received webhooks",
		IndicatorWidget_r66edu6_template: "{0}",
		IndicatorWidget_r66edu6_title: "Failed (last month)",
		IndicatorWidget_22ylllo_template: "{0}",
		IndicatorWidget_22ylllo_title: "Done (last month)",
		IndicatorWidget_bjb3cer_template: "{0}",
		IndicatorWidget_bjb3cer_title: "Total (last month)",
		ExpansionPanel_4zutypr_title: "Expansion panel",
		GridDetailSearchFilter_ck9immr_placeholder: "Search",
		GridDetailImportDataBtn_3rzdc5d_caption: "Data import",
		GridDetailExportDataBtn_vb3dzyx_caption: "Export to Excel",
		GridDetailSettingsBtn_v4qh0vz_caption: "Actions",
		GridDetailRefreshBtn_ory6ucl_caption: "Refresh",
		GridDetailAddBtn_ftrhsgt_caption: "New",
		ExpansionPanel_g6w8vv2_title: "Expanded list",
		GridDetailSearchFilter_lndyqse_placeholder: "Search",
		GridDetailImportDataBtn_x02907f_caption: "Data import",
		GridDetailExportDataBtn_fepioay_caption: "Export to Excel",
		GridDetailSettingsBtn_ipy1y7c_caption: "Actions",
		GridDetailRefreshBtn_sdhf8d7_caption: "Refresh",
		GridDetailAddBtn_vleb49o_caption: "New",
		ExpansionPanel_72otv46_title: "Expanded list",
		GridDetailSearchFilter_ud5ymxi_placeholder: "Search",
		GridDetailImportDataBtn_9oaeyn1_caption: "Data import",
		GridDetailExportDataBtn_qq7bdrg_caption: "Export to Excel",
		GridDetailSettingsBtn_2n81ep0_caption: "Actions",
		GridDetailRefreshBtn_fb2vvmp_caption: "Refresh",
		GridDetailAddBtn_7nkzey9_caption: "New",
		ExpansionPanel_kjwmbcu_title: "Expanded list",
		GridDetailSearchFilter_qkxogy2_placeholder: "Search",
		GridDetailImportDataBtn_nxm4v3d_caption: "Data import",
		GridDetailExportDataBtn_vbq44zn_caption: "Export to Excel",
		GridDetailSettingsBtn_0m5pjwm_caption: "Actions",
		GridDetailRefreshBtn_8oc3epz_caption: "Refresh",
		GridDetailAddBtn_fmjyr4d_caption: "New",
		ExpansionPanel_1bjbj0p_title: "Webhooks",
		Label_g409zkw_caption: "Label 2",
		TabContainer_f7bqc03_caption: "Tab 2",
		Label_y97mh2y_caption: "Help",
		TabContainer_gtby4w5_caption: "Help",
		RefreshButton_caption: "Refresh",
		MenuItem_z1phikt_caption: "Webhoo",
		QuickFilter_9qjwg9x_config_caption: "Date  range",
		QuickFilter_9qjwg9x_caption: "Quick filter",
		FolderTree_guynq9k_caption: "Folders",
		QuickFilter_3qpzxap_caption: "Quick filter",
		Label_1li6b1j_caption: "Label 2",
		TabContainer_o1bnuuz_caption: "Tab 2",
		Label_6cq6qgu_caption: "Label 1",
		TabContainer_0xx53ei_caption: "Tab 1",
		Label_xls3uj6_caption: "Help",
		Label_mh1ws7l_caption: "You can receive or send messages using the Webhooks mechanism. Customized webhooks must be used in business processes to build a complete script for working with a webhook.",
		TabContainer_uo7005y_caption: "Help",
		Label_ahmt4sl_caption: "You can receive or send messages using the Webhooks mechanism. Customized webhooks must be used in business processes to build a complete script for working with a webhook.",
		Label_0sv43fq_caption: "More details about working with webhooks can be found in the documentation.",
		Label_ex7d26c_caption: "All outcoming and incoming messages will be stored in the [Webhook] table.",
		Label_fs60bhd_caption: "To receive a message in Creatio, configure the incoming flow.  In the Webhook URL field, a unique endpoint will be generated to which you need to send a message.",
		Label_p2q6emt_caption: "To send a message from Creatio, configure the outcoming flow.  In the Webhook URL field, you must specify the external endpoint to which the message will be sent from Creatio.",
		Label_5gp44vn_caption: "How to get a webhook",
		GridDetailSearchFilter_2qcgscw_placeholder: "Search",
		GridDetailImportDataBtn_38dp5a8_caption: "Open logs",
		GridDetailExportDataBtn_3bu9sj8_caption: "Export to Excel",
		GridDetailSettingsBtn_0eplzmc_caption: "Actions",
		GridDetailRefreshBtn_7scy2pn_caption: "Refresh",
		GridDetailAddBtn_1pz6zpp_caption: "New",
		ExpansionPanel_38uo2qz_title: "Webhooks",
		ExpansionPanel_vy8amoc_title: "Expansion panel",
		Label_j307vrt_caption: "Webhooks",
		GridDetailSearchFilter_tolonc9_placeholder: "Search",
		GridDetailImportDataBtn_va1cb1k_caption: "Data import",
		GridDetailExportDataBtn_rc57ift_caption: "Export to Excel",
		GridDetailSettingsBtn_jyda1fq_caption: "Actions",
		GridDetailRefreshBtn_jp8uiim_caption: "Refresh",
		GridDetailAddBtn_60ofqbw_caption: "New",
		ExpansionPanel_a03f5th_title: "Webhooks",
		Label_g9kd6kf_caption: "Webhooks",
		SearchFilter_7kbe87n_ud5ymxi_placeholder: "Search",
		SearchFilter_7kbe87n_tolonc9_placeholder: "Search",
		SearchFilter_7kbe87n_qkxogy2_placeholder: "Search",
		SearchFilter_7kbe87n_lndyqse_placeholder: "Search",
		SearchFilter_7kbe87n_ck9immr_placeholder: "Search",
		SearchFilter_7kbe87n_2qcgscw_placeholder: "Search",
		Button_3vperg8_sdhf8d7_caption: "Refresh",
		Button_3vperg8_ory6ucl_caption: "Refresh",
		Button_3vperg8_jp8uiim_caption: "Refresh",
		Button_3vperg8_fb2vvmp_caption: "Refresh",
		Button_3vperg8_8oc3epz_caption: "Refresh",
		Button_3vperg8_7scy2pn_caption: "Refresh",
		MenuItem_stn1mjo_caption: "Open logs",
		MenuItem_yhiv1sr_caption: "Export to Excel",
		Button_mm0e6os_v4qh0vz_caption: "Actions",
		Button_mm0e6os_jyda1fq_caption: "Actions",
		Button_mm0e6os_ipy1y7c_caption: "Actions",
		Button_mm0e6os_2n81ep0_caption: "Actions",
		Button_mm0e6os_0m5pjwm_caption: "Actions",
		Button_mm0e6os_0eplzmc_caption: "Actions",
		WebhookDynamicsChartWidget_yAxis: "Count of webhooks",
		WebhookDynamicsChartWidget_xAxis: "Date",
		WebhookDynamicsChartWidget_series_0: "Total",
		WebhookDynamicsChartWidget_title: "Dynamics of received webhooks",
		FailedIndicatorWidget_template: "{0}",
		FailedIndicatorWidget_title: "Failed",
		DoneIndicatorWidget_template: "{0}",
		DoneIndicatorWidget_title: "Done",
		TotalIndicatorWidget_template: "{0}",
		TotalIndicatorWidget_title: "Total",
		QuickFilter_8s232ng_config_caption: "Status",
		QuickFilter_8s232ng_caption: "Quick filter",
		DateRangeQuickFilter_config_caption: "Date range",
		WebhookStatusQuickFilter_config_caption: "Status",
		SearchFilter_7kbe87n_placeholder: "Search",
		Button_3vperg8_caption: "Refresh",
		MenuItem_59sp0kg_caption: "Open logs",
		MenuItem_9a4pwfl_caption: "Export to Excel",
		MenuItem_kv0dpv5_caption: "Open logs",
		MenuItem_4dxku1w_caption: "Export to Excel",
		QuickFilter_58o5d9d_config_caption: "Status",
		WebhookDynamicsChartWidget_series_2: "Failed",
		WebhookDynamicsChartWidget_series_1: "Done",
		Button_tm5wk65_caption: "Connect webhooks",
		GridSearchFilter_placeholder: "Search",
		GridRefreshButton_caption: "Refresh",
		GridLabel_caption: "Webhooks",
		HelpTabContainer_caption: "Help",
		GridAcionButton_caption: "Actions",
		Label_oafgqcb_caption: "Learn more about working with webhooks in the Academy:",
		Label_g2onp2t_caption: "You can customize the logic that handles webhooks based on the \u201CCreate object records based on incoming webhook\u201D business process.",
		HelpTabDataLabel5_caption: "View the results of received and handled webhooks in the \u201CWebhooks\u201D section.",
		HelpTabDataLabel4_caption: "where:",
		Label_1x3qut4_caption: "List of parameters that define the entity fields to record. Name the attributes similarly to the field codes of the needed entity.",
		Label_w38r2qp_caption: "\u2022",
		Label_jlwxf98_caption: "\u201CEntityName.\u201D Defines the entity to add records based on webhook data. Set the parameter value to the code of the needed entity.",
		Label_9wgs5dw_caption: "\u2022",
		Label_hcam16u_caption: "\u201CNew user\u201D, \u201Cnew_user@creatio.com\u201D, \u201C\u002B1 617 221 5187\u201D are the values to record to the \u201CName\u201D, \u201CEmail\u201D, \u201CMobilePhone\u201D fields in the \u201CContact\u201D entity.",
		Label_0a06vv6_caption: "\u2022",
		Label_91s5zcf_caption: "\u201CName\u201D, \u201CEmail\u201D, \u201CMobilePhone\u201D parameters match the \u201CFull Name\u201D, \u201CEmail\u201D, \u201CPhone\u201D fields of the \u201CContact\u201D entity.",
		Label_35jjfa5_caption: "\u2022",
		Label_tiw261a_caption: "\u201CEntityName\u201D parameter defines the \u201CContact\u201D Creatio entity.",
		Label_i4kvftd_caption: "\u2022",
		Label_nrszjiz_caption: "\u0022Name\u0022:\u0022New user\u0022,  \u0022Email\u0022:new_user@creatio.com,  \u0022MobilePhone\u0022:\u0022\u002B1 617 221 5187\u0022,  \u0022EntityName\u0022:\u0022Contact\u0022",
		HelpTabDataLabel3_caption: "View an example of the webhook body parameters that Creatio can parse below.",
		Label_yrdd796_caption: "List of parameters that define the entity fields to record. Attribute names must match the values \u200B\u200Bof field codes of the needed entity",
		Label_ekem5kk_caption: "\u2022",
		Label_htsmiti_caption: "\u201CEntityName.\u201D Defines the entity to add records based on webhook data. Set the parameter value to the code of the needed entity.",
		Label_qhakaal_caption: "\u2022",
		Label_8mn09ly_caption: "\u201CEntityName.\u201D Defines the entity to add records based on webhook data. The value of the parameter must correspond to the \u0022Code\u0022 of the needed entity.",
		Label_z2h0x3a_caption: "\u2022",
		Label_8o37a2u_caption: "Webhook request body must contain the following parameters:",
		Label_vppw3wj_caption: "Webhook request body must contain the following parameters:",
		Label_e52xppb_caption: "\u2022",
		Label_vj8qxrg_caption: "JSON and FormData data types of the request must be supported.",
		Label_ugbalq5_caption: "JSON and FormData data types of the request must be supported.",
		Label_23a6gea_caption: "\u2022",
		Label_ho0hkdq_caption: "Send data to the generated Webhook URL via a POST request.",
		Label_pm3dklv_caption: "\u2022",
		Label_dxstmow_caption: "Send data to the generated Webhook URL via a POST request.",
		Label_dkxrxwy_caption: " \u2022",
		HelpTabDataLabel2_caption: "Make sure the webhooks meet the following requirements:",
		HelpTabDataLabel1_caption: "Use webhooks to import data from an external service to any Creatio section or other entity. Creatio handles the received webhook and creates a record of the needed entity automatically.",
		Label_mkoc91k_caption: "Process webhooks in Creatio",
		Label_ovkk9qg_caption: " via a POST request.",
		Label_7habo7b_caption: "Webhook URL ",
		HelpWebhookRequirementItemText1_caption: "Send data to the generated ",
		RichTextEditor_q02s89l_label: "Rich text",
		RichTextEditor_q02s89l_caption: "Rich text",
		Input_vnyfi2v_label: "Text",
		Button_ikpvshe_caption: "Webhook URL",
		HelpTabDataLabel7LearnMore_caption: "Learn more about working with webhooks in the Academy:",
		HelpTabDataLabel6CustomizeWebhook_caption: "You can customize the logic that handles webhooks based on the \u201CCreate object records based on incoming webhook\u201D business process.",
		HelpTabDataLabel5WebhookSection_caption: "View the results of received and handled webhooks in the \u201CWebhooks\u201D section.",
		HelpWebhookFornoteItemText3_caption: "\u201CNew user\u201D, \u201Cnew_user@creatio.com\u201D, \u201C\u002B1 617 221 5187\u201D are the values to record to the \u201CName\u201D, \u201CEmail\u201D, \u201CMobilePhone\u201D fields in the \u201CContact\u201D entity.",
		HelpWebhookFornoteItemText2_caption: "\u201CName\u201D, \u201CEmail\u201D, \u201CMobilePhone\u201D parameters match the \u201CFull Name\u201D, \u201CEmail\u201D, \u201CPhone\u201D fields of the \u201CContact\u201D entity.",
		HelpWebhookFornoteItemText1_caption: "\u201CEntityName\u201D parameter defines the \u201CContact\u201D Creatio entity.",
		HelpWebhookRequirementItemText5_caption: "List of parameters that define the entity fields to record. Attribute names must match the values \u200B\u200Bof field codes of the needed entity",
		HelpWebhookRequirementItemText4_caption: "\u201CEntityName.\u201D Defines the entity to add records based on webhook data. The value of the parameter must correspond to the \u0022Code\u0022 of the needed entity.",
		HelpWebhookRequirementItemText3_caption: "Webhook request body must contain the following parameters:",
		HelpWebhookRequirementItemText2_caption: "JSON and FormData data types of the request are supported.",
		HelpWebhookRequirementItemText1_3_caption: " via a POST request.",
		HelpWebhookRequirementItemText1_1_caption: "Send data to the generated ",
		ActionButton_caption: "Actions",
		Button_Data_Import: "Import",
		DefaultHeaderCaption: "Page title",
		EmptySectionPlaceholderSubHead: "Add a new record to make it look prettier",
		EmptySectionPlaceholderTitle: "The section has no records",
		FilteredEmptySectionPlaceholderSubHead: "Clear the filter or change its conditions",
		FilteredEmptySectionPlaceholderTitle: "There are no records matching the filter criteria",
		ListTitleCaption: "List title",
		MenuItem_ExportToExel_caption: "Export to Excel",
		MenuItem_ImportFromExel_caption: "Excel",
		OpenLandingDesignerCaption: "Web forms and pages"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});