define("AutoGeneratedPageUserTaskButtonMiniEditPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		NameCaption: "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435",
		CodeCaption: "\u041A\u043E\u0434",
		StyleCaption: "\u0421\u0442\u0438\u043B\u044C",
		GenerateSignalCaption: "\u0413\u0435\u043D\u0435\u0440\u0438\u0440\u0443\u0435\u0442 \u0441\u0438\u0433\u043D\u0430\u043B",
		IsEnabledCaption: "\u0410\u043A\u0442\u0438\u0432\u043D\u0430\u044F",
		PerformValidationCaption: "\u0412\u044B\u043F\u043E\u043B\u043D\u044F\u0435\u0442 \u043F\u0440\u043E\u0432\u0435\u0440\u043A\u0443 \u0437\u043D\u0430\u0447\u0435\u043D\u0438\u0439"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});