define("AutoGeneratedPageV2UtilitiesResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		UnsupportedType: "\u0422\u0438\u043F \u043D\u0435 \u043F\u043E\u0434\u0434\u0435\u0440\u0436\u0438\u0432\u0430\u0435\u0442\u0441\u044F"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});