define("AutoGeneratedPageUserTaskElementViewModelResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		SelectFromLookupTypeCaption: "\u0412\u044B\u0431\u043E\u0440 \u0437\u043D\u0430\u0447\u0435\u043D\u0438\u044F \u0438\u0437 \u0441\u043F\u0440\u0430\u0432\u043E\u0447\u043D\u0438\u043A\u0430",
		DropDownListTypeCaption: "\u0412\u044B\u0431\u043E\u0440 \u0437\u043D\u0430\u0447\u0435\u043D\u0438\u044F \u0438\u0437 \u0441\u043F\u0438\u0441\u043A\u0430",
		DateAndTimeFormatCaption: "\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043C\u044F",
		DateFormatCaption: "\u0414\u0430\u0442\u0430",
		TimeFormatCaption: "\u0412\u0440\u0435\u043C\u044F",
		ItemFloderLabelCaption: "\u0413\u0440\u0443\u043F\u043F\u0430 \u043F\u043E\u043B\u0435\u0439",
		NotesLabelCaption: "\u041A\u043E\u043C\u043C\u0435\u043D\u0442\u0430\u0440\u0438\u0439"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});