define("AutoGeneratedPageUserTaskElementMiniEditPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		CaptionCaption: "\u0417\u0430\u0433\u043E\u043B\u043E\u0432\u043E\u043A",
		NameCaption: "\u041A\u043E\u0434",
		TextCaption: "\u0422\u0435\u043A\u0441\u0442",
		IsMultilineCaption: "\u041C\u043D\u043E\u0433\u043E\u0441\u0442\u0440\u043E\u0447\u043D\u043E\u0435",
		IsRequiredCaption: "\u041E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u043E\u0435",
		CanBeMinimizedCaption: "\u041C\u043E\u0436\u0435\u0442 \u0431\u044B\u0442\u044C \u0441\u0432\u0435\u0440\u043D\u0443\u0442\u0430",
		MinimizedCaption: "\u0421\u0432\u0435\u0440\u043D\u0443\u0442\u0430",
		DataSourceCaption: "\u0418\u0441\u0442\u043E\u0447\u043D\u0438\u043A \u0434\u0430\u043D\u043D\u044B\u0445",
		ControlDataValueTypeCaption: "\u0412\u0438\u0434",
		DateTimeFormatCaption: "\u0424\u043E\u0440\u043C\u0430\u0442 \u0434\u0430\u0442\u044B",
		ValueCaption: "\u0417\u043D\u0430\u0447\u0435\u043D\u0438\u0435"
	};
	var parametersLocalizableStrings = {};
	var localizableImages = {};
	return {localizableStrings: localizableStrings, localizableImages: localizableImages, parametersLocalizableStrings: parametersLocalizableStrings};
});